apiVersion: apps/v1
kind: Deployment
metadata:
  name: olm
  namespace: newt
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olm
  template:
    metadata:
      labels:
        app: olm
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "worker"
      hostNetwork: true
      containers:
        - name: olm
          image: fosrl/olm:latest
          imagePullPolicy: Always
          env:
            - name: PANGOLIN_ENDPOINT
              value: "https://pangolin.elmstreet79.de"
            - name: OLM_ID
              valueFrom:
                secretKeyRef:
                  name: newt-auth
                  key: id
            - name: OLM_SECRET
              valueFrom:
                secretKeyRef:
                  name: newt-auth
                  key: secret
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: tun
              mountPath: /dev/net/tun
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
      volumes:
        - name: tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
