apiVersion: apps/v1
kind: Deployment
metadata:
  name: newt
  namespace: newt
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newt
  template:
    metadata:
      labels:
        app: newt
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "worker"
      containers:
        - name: newt
          image: fosrl/newt:latest
          imagePullPolicy: Always
          env:
            - name: PANGOLIN_ENDPOINT
              value: "https://pangolin.elmstreet79.de"
            - name: NEWT_ID
              valueFrom:
                secretKeyRef:
                  name: newt-auth
                  key: id
            - name: NEWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: newt-auth
                  key: secret
            - name: ACCEPT_CLIENTS
              value: "true"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
