---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fr24
  namespace: private-services
  annotations:
    cert-manager.io/cluster-issuer: internal-ca-issuer
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - fr24.elmstreet79.de
      secretName: fr24-tls
  rules:
    - host: fr24.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fr24
                port:
                  number: 80
