---
apiVersion: v1
kind: Service
metadata:
  name: glances-macmini
  namespace: private-services
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 61208
      targetPort: 61208
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glances-macmini
  namespace: private-services
subsets:
  - addresses:
      - ip: 192.168.2.4
    ports:
      - name: http
        port: 61208
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glances-macmini
  namespace: private-services
  annotations:
    cert-manager.io/cluster-issuer: internal-ca-issuer
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - glances-macmini.elmstreet79.de
      secretName: glances-macmini-tls
  rules:
    - host: glances-macmini.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glances-macmini
                port:
                  number: 61208
