apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: private-services
resources:
  - teslalogger-ingress.yaml
  - dreambox-ingress.yaml
  - adguard-external-service.yaml
  - adguard-ingress.yaml
  - beszel-external-service.yaml
  - beszel-ingress.yaml
  - minio-external-service.yaml
  - minio-ingress.yaml
  - proxmox-external-service.yaml
  - proxmox-ingress.yaml
  - macmini-external-service.yaml
  - macmini-ingress.yaml
  - homebridge-external-service.yaml
  - homebridge-ingress.yaml
  - fr24-external-service.yaml
  - fr24-ingress.yaml
  - glances-external-service.yaml
  - glances-ingress.yaml
  - adguard-credentials-sealed.yaml
  - adguard-dns-sync-rbac.yaml
  - adguard-dns-sync-job.yaml
  - teslalogger-web-external-service.yaml
  - teslalogger-web-ingress.yaml
