apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: private-services
resources:
  - internal-cluster-issuer.yaml
  - teslalogger-ingress.yaml
  - dreambox-ingress.yaml
  - adguard-ingress.yaml
  - beszel-ingress.yaml
  - minio-ingress.yaml
  - proxmox-ingress.yaml
  - adguard-macmini-ingress.yaml
  - homebridge-ingress.yaml
  - fr24-ingress.yaml
  - glances-macmini-ingress.yaml
  - unifi-ingress.yaml
  - adguard-credentials-sealed.yaml
  - adguard-dns-sync-rbac.yaml
  - adguard-dns-sync-job.yaml
  - teslalogger-web-ingress.yaml
  - adguard-home-sync-ingress.yaml
