apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: private-services
resources:
  - internal-cluster-issuer.yaml
  - servers-transport-insecure.yaml
  - minio-middleware.yaml
  - traefik-dashboard-certificate.yaml
  - dreambox-ingress.yaml
  - adguard-ingress.yaml
  - beszel-ingress.yaml
  - minio-ingress.yaml
  - proxmox-ingress.yaml
  - adguard-macmini-ingress.yaml
  - fr24-ingress.yaml
  - glances-macmini-ingress.yaml
  - unifi-ingress.yaml
  - wazuh-ingress.yaml
  - adguard-credentials-sealed.yaml
  - adguard-dns-sync-rbac.yaml
  - adguard-dns-sync-job.yaml
  - adguard-sync-ingress.yaml
  - tesla-key-configmap.yaml
  - tesla-key-deployment.yaml
  - tesla-key-ingress.yaml
