apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: private-services
resources:
  - teslalogger-ingress.yaml
  - dreambox-ingress.yaml
  - adguard-external-service.yaml
  - adguard-ingress.yaml
  - beszel-external-service.yaml
  - beszel-ingress.yaml
  - adguard-credentials-sealed.yaml
  - adguard-dns-sync-rbac.yaml
  - adguard-dns-sync-job.yaml
