---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: macmini
  namespace: private-services
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: macmini.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: macmini
                port:
                  number: 80
