---
apiVersion: v1
kind: Service
metadata:
  name: minio-pi5-api
  namespace: private-services
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 80
      targetPort: 9300
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: minio-pi5-api
  namespace: private-services
subsets:
  - addresses:
      - ip: 192.168.2.9
    ports:
      - name: api
        port: 9300
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: minio-pi5-console
  namespace: private-services
spec:
  type: ClusterIP
  ports:
    - name: console
      port: 80
      targetPort: 9393
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: minio-pi5-console
  namespace: private-services
subsets:
  - addresses:
      - ip: 192.168.2.9
    ports:
      - name: console
        port: 9393
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-pi5-api
  namespace: private-services
  annotations:
    cert-manager.io/cluster-issuer: internal-ca-issuer
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - minio-api.elmstreet79.de
      secretName: minio-pi5-api-tls
  rules:
    - host: minio-api.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-pi5-api
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-pi5-console
  namespace: private-services
  annotations:
    cert-manager.io/cluster-issuer: internal-ca-issuer
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "MinIO"
    gethomepage.dev/description: "S3 Object Storage"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "minio.png"
    gethomepage.dev/weight: "60"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - minio.elmstreet79.de
      secretName: minio-pi5-console-tls
  rules:
    - host: minio.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-pi5-console
                port:
                  number: 80
