---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teslalogger-web
  namespace: private-services
  annotations:
    cert-manager.io/cluster-issuer: internal-ca-issuer
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - teslalogger-web.elmstreet79.de
      secretName: teslalogger-web-tls
  rules:
    - host: teslalogger-web.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teslalogger-web
                port:
                  number: 80
