apiVersion: v1
kind: ConfigMap
metadata:
  name: tesla-key
  namespace: private-services
data:
  com.tesla.3p.public-key.pem: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEh+sEX/AJYmgiF72BXdXqs8b6mK1M
    RaA+lYFSOUMyjxccIzgEYScnRcCLEVsRs45jIJgNNThdhje68ZMy4y0pkQ==
    -----END PUBLIC KEY-----
  
  nginx.conf: |
    server {
      listen 80;
      server_name tesla-key.elmstreet79.de;
      
      location /.well-known/appspecific/com.tesla.3p.public-key.pem {
        root /usr/share/nginx/html;
        try_files /com.tesla.3p.public-key.pem =404;
        add_header Content-Type application/x-pem-file;
        add_header Access-Control-Allow-Origin *;
      }
      
      location / {
        return 404;
      }
    }
