---
apiVersion: v1
kind: Service
metadata:
  name: teslalogger-external
  namespace: private-services
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: teslalogger-external
  namespace: private-services
  labels:
    argocd.argoproj.io/instance: private-services
subsets:
  - addresses:
      - ip: 192.168.2.9
    ports:
      - port: 3000
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teslalogger
  namespace: private-services
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - teslalogger.elmstreet79.de
      secretName: teslalogger-tls
  rules:
    - host: teslalogger.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teslalogger-external
                port:
                  number: 3000
