apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tesla-key
  namespace: private-services
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tesla-key.elmstreet79.de
      secretName: tesla-key-tls
  rules:
    - host: tesla-key.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tesla-key
                port:
                  number: 80
