---
apiVersion: v1
kind: Service
metadata:
  name: unifi
  namespace: private-services
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: unifi
  namespace: private-services
subsets:
  - addresses:
      - ip: 192.168.2.1
    ports:
      - name: https
        port: 443
        protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: unifi
  namespace: private-services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`unifi.elmstreet79.de`)
      kind: Rule
      services:
        - name: unifi
          port: 443
          scheme: https
          serversTransport: insecure-transport
  tls:
    secretName: unifi-tls
---
# Dummy Ingress for DNS sync and cert-manager
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi-dns
  namespace: private-services
  annotations:
    cert-manager.io/cluster-issuer: internal-ca-issuer
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - unifi.elmstreet79.de
      secretName: unifi-tls
  rules:
    - host: unifi.elmstreet79.de
      http:
        paths:
          - path: /__dns_sync_only__
            pathType: Exact
            backend:
              service:
                name: unifi
                port:
                  number: 443
