apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ntfy
  namespace: ntfy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "15m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "ntfy"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "ntfy"
    gethomepage.dev/description: "Push Notifications"
    gethomepage.dev/group: "Services"
    gethomepage.dev/icon: "https://cdn.simpleicons.org/ntfy/317F6F"
    gethomepage.dev/weight: "40"
    gethomepage.dev/pod-selector: "app=ntfy"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ntfy.elmstreet79.de
      secretName: ntfy-tls
  rules:
    - host: ntfy.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ntfy
                port:
                  number: 8338
