apiVersion: apps/v1
kind: Deployment
metadata:
  name: fr24feed
  namespace: fr24
  labels:
    app: fr24feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fr24feed
  template:
    metadata:
      labels:
        app: fr24feed
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "worker"
      containers:
      - name: fr24feed
        image: ghcr.io/sdr-enthusiasts/docker-flightradar24:latest-build-825
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8754
          name: http
          protocol: TCP
        env:
        - name: BEASTHOST
          value: "192.168.2.9"
        - name: FR24KEY
          valueFrom:
            secretKeyRef:
              name: fr24-secret
              key: fr24-key
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
