---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fr24-secret
  namespace: fr24
spec:
  encryptedData:
    fr24-key: AgCKjcFoBaAExKyMDSsKw9BuUJzt/84+hnnWNETODYGPdkE+IXnEj2PJaoxHP2KIPMcdIKYn9gRMaxvi0u8qEw+X3pghxXt/aHDx3Mn89jwyHVxxppDGGOkqrXwqLFevnkBSHr+f/m1sBgeGYo2EgSdJke/mQPsrCD+423/MfR71pj3COnUUxx3hmsRt1oFq3leIEl3k9hVAXP0l6vffXS6b9ELPr850c8XksE7LVu/Gwi2nvyntX1J3YA6WoYINzEXLwYkKvtp5QLh3MswRF9abakAsKfRjeJY6bZtrWi+IPAJyqRdUJsT8EjUqCMfgET8vryeJK2ppJSGI/XRfs3n6ISfNqyoMP8yeJEb9qYjzfy0DdmoBzOWeAhXVaOYPgONatb/cXCmChgvw+/PDVRU4RMYdN4gYs2hFLXWsqguHE9o8XQ8+gcP4u3tLA57aOMFKjm+A7D42pz4ke7PvsMvOUknjBDuRrx5uHTghV/z5pfwZGq/5P2LGV71Zi1cnWn4ZRGbf06IEl7qnbj2PFoAm29YStdwIS0pwB8N7tHEV6u9K7zDIh/SiXQeqMO6wpvRXRcdsK1OH8HiFVQV6b/u9v8i2LN5pGKSda4TFWcK5lFKWgEuJtrw90TESiKgXvRq3dYkDc2eja0mpMHVWgMYmqLqzG2lthfERhkuZszCVsJRZ3AhQ6uXuxxQAiXH/vAs3QsBRpqjX8trADKRhLkCq
  template:
    metadata:
      name: fr24-secret
      namespace: fr24
    type: Opaque
