apiVersion: v1
kind: Service
metadata:
  name: fr24feed
  namespace: fr24
  labels:
    app: fr24feed
spec:
  type: ClusterIP
  ports:
  - port: 8754
    targetPort: 8754
    protocol: TCP
    name: http
  selector:
    app: fr24feed
