---
apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-stack-grafana
  namespace: monitoring
  annotations:
    pangolin.io/expose: "true"
    pangolin.io/subdomain: "grafana"
    pangolin.io/auth: "true"
