apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxmox-exporter
  namespace: monitoring
  labels:
    app: proxmox-exporter
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxmox-exporter
  template:
    metadata:
      labels:
        app: proxmox-exporter
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "worker"
      containers:
        - name: pve-exporter
          image: bigtcze/pve-exporter:latest
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          env:
            - name: PVE_HOST
              valueFrom:
                secretKeyRef:
                  name: pve-api-credentials
                  key: target
            - name: PVE_USER
              valueFrom:
                secretKeyRef:
                  name: pve-api-credentials
                  key: username
            - name: PVE_TOKEN_NAME
              value: "exporter"
            - name: PVE_TOKEN_VALUE
              valueFrom:
                secretKeyRef:
                  name: pve-api-credentials
                  key: password
            - name: PVE_VERIFY_SSL
              value: "false"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
