apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: proxmox-exporter
  namespace: monitoring
  labels:
    app: proxmox-exporter
spec:
  selector:
    matchLabels:
      app: proxmox-exporter
  endpoints:
    - port: metrics
      interval: 60s
      scrapeTimeout: 30s
      params:
        module: [default]
