apiVersion: v1
kind: Service
metadata:
  name: proxmox-exporter
  namespace: monitoring
  labels:
    app: proxmox-exporter
spec:
  selector:
    app: proxmox-exporter
  ports:
    - name: metrics
      port: 9221
      targetPort: metrics
      protocol: TCP
