apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: proxmox-exporter
  namespace: monitoring
  labels:
    app: proxmox-exporter
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: proxmox-exporter
  endpoints:
    - port: metrics
      interval: 60s
      scrapeTimeout: 90s
      path: /pve
      params:
        target: ['192.168.2.8']  # Proxmox host
        module: ['default']
        cluster: ['1']
        node: ['1']
