apiVersion: v1
kind: Service
metadata:
  name: ntfy
  labels:
    app: ntfy
spec:
  type: ClusterIP
  selector:
    app: ntfy
  ports:
  - port: 8338
    targetPort: http
    protocol: TCP
    name: http
