apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Uptime Kuma"
    gethomepage.dev/description: "Uptime Monitoring"
    gethomepage.dev/group: "Monitoring"
    gethomepage.dev/icon: "uptime-kuma.png"
    gethomepage.dev/weight: "50"
    gethomepage.dev/widget.type: "uptimekuma"
    gethomepage.dev/widget.url: "https://uptime.elmstreet79.de"
    gethomepage.dev/widget.slug: "homelab"
    gethomepage.dev/ping: uptime-kuma.uptime-kuma.svc.cluster.local
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - uptime.elmstreet79.de
      secretName: uptime-kuma-tls
  rules:
    - host: uptime.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma
                port:
                  number: 3001
