apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: teslamate

resources:
  - namespace.yaml
  - database-pvc.yaml
  - grafana-pvc.yaml
  - mosquitto-pvc.yaml
  - database-deployment.yaml
  - mosquitto-deployment.yaml
  - teslamate-deployment.yaml
  - grafana-deployment.yaml
  - teslamate-ingress.yaml
  - grafana-ingress.yaml
  - teslamate-secret-sealed.yaml
