apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teslamate
  namespace: teslamate
  annotations:
    cert-manager.io/cluster-issuer: internal-ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "TeslaMate Settings"
    gethomepage.dev/description: "Tesla Tracking & Analytics"
    gethomepage.dev/group: "Applications - Intern"
    gethomepage.dev/icon: "teslamate.png"
    gethomepage.dev/weight: "11"
    gethomepage.dev/pod-selector: "app=teslamate"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - teslamate-settings.elmstreet79.de
      secretName: teslamate-tls
  rules:
    - host: teslamate-settings.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teslamate
                port:
                  number: 4000
