apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing-page
  namespace: landing-page
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - www.elmstreet79.de
        - elmstreet79.de
      secretName: landing-page-tls
  rules:
    - host: www.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing-page
                port:
                  number: 80
    - host: elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing-page
                port:
                  number: 80
