apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beszel-hub
  namespace: beszel
  labels:
    app: beszel-hub
  annotations:
    cert-manager.io/cluster-issuer: internal-ca-issuer
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - beszel-k8s.elmstreet79.de
    secretName: beszel-hub-tls
  rules:
  - host: beszel-k8s.elmstreet79.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: beszel-hub
            port:
              name: http
