apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beszel-hub
  namespace: beszel
  labels:
    app: beszel-hub
  annotations:
    cert-manager.io/cluster-issuer: internal-ca-issuer
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Monitoring
    gethomepage.dev/name: Beszel K8s
    gethomepage.dev/icon: beszel.png
    gethomepage.dev/description: System Monitor
    gethomepage.dev/weight: "41"
    gethomepage.dev/pod-selector: "app=beszel-hub"
    gethomepage.dev/widget.type: beszel
    gethomepage.dev/widget.url: https://beszel-k8s.elmstreet79.de
    gethomepage.dev/widget.username: "{{HOMEPAGE_VAR_BESZEL_USERNAME}}"
    gethomepage.dev/widget.password: "{{HOMEPAGE_VAR_BESZEL_PASSWORD}}"
    gethomepage.dev/widget.version: "2"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - beszel-k8s.elmstreet79.de
    secretName: beszel-hub-tls
  rules:
  - host: beszel-k8s.elmstreet79.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: beszel-hub
            port:
              name: http
