apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: beszel

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secret-sealed.yaml
  - agent-daemonset.yaml

commonLabels:
  app.kubernetes.io/name: beszel
  app.kubernetes.io/component: monitoring
