apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beszel-data
  namespace: beszel
  labels:
    app: beszel-hub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: ""  # Uncomment and specify if you want a specific storage class
