# This file should be replaced by secret-sealed.yaml after sealing
# See secret-unsealed.yaml for the template
# Command: kubeseal --format=yaml --controller-namespace=kube-system < manifests/beszel/secret-unsealed.yaml > manifests/beszel/secret-sealed.yaml
