---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: beszel-agent-ssh
  namespace: beszel
spec:
  encryptedData:
    SSH_PUBLIC_KEY: AgAWnmQNqgzR/HPyW++dl3oxXbX83AiKxhZ7uaPcPCt7VwYjIHfMLy803wEk++NFi7u0Z1Y0jiFeRIBsk1kYbX4iNF3Ugw4XGqqrPjP2s3BwxJIWc9+9wRQrysRKk2CVi0HbGpmsh7V4gu9pa7fOzkisywndWmLy0A393m9dW6Nzvqtx64B3vgT/QYmtjjBn3+vlsBdy167T9Bj3029m3gQAHxt06XRbeN3JxT0gg1MUoQJDpJnvKkoQ72OTh7/blRc5t7U7kt41e20N3NsswTJA4fVfvF0hmRCQINWfE99ycIY3euv41+Sq5GX0IdnfaM7lTtzlY0q/6kB1IaBNxU1SvIy8zsj7DRHZz4iFX9oOM7mpRCr4AoO1REeowXjZbs7dopxlGMph9aW03ijySx2ks2yK2GIY7KagPxd+j0hRcNf0Jub0Yg1wF3K0jg19xOYvAuWPFAMSMn4KRC0OmdGekIb1rxz1jGoC2hkiEb0dWonBs1ieitKaLUZJRKTfc5kgUqYuL6MIfue6GozOjwi/tAOr0WYKbo7goGHaLgCuEEDPlfuqRdR6YNmxUYuNRp6FTHp7RlUePTd1sa/QEKEMHNqRs+oh2F6sgPSbnkAzO7OMORT5E2hVD7iUR0idE4/nzRD8zc5tqwIfenjEWzDw2/dOw944ZNe5Cp2kL4gY6UNdmy4LQhRRr67iQgpHCcF+Fyuofk/htLL6vAsPr2KGU2LGZz23JPt8ErmkttOjB/zuJ3ASp56B2RGsUZSPF9TmJ68Co1NTqevvr3jrfLIaSHPuQ9tYDHOCJ0wVjsBUNQ==
    TOKEN: AgChODurd/rt49fFaktQORZtEM23mI7f4kzIX89rLwPeIRvF4UE0kZvFkVhO7S6GsHwbO5eD8kKhU4ktisAeq9IY5CPy4Tmxu0y6VYotyrwmj8tTCPezMotWVHWBlKOK6kw3qQbLd2qA2M32h2ZwTfMO8sGITOjAWzi3ZcSQrUf9EMx6/8+x7O6HTBFterqifKDH7vZJs4duhDS2v8RWot62/xhvWWZ2zIEN/AGXLU95eOHz/4JJBUGpCMuOjavaaNf+USn4TNsInNuvYLvJ9Z/HcibjMcHftePHrEFze2LU2koBGdUcAK392nQlW/ziw2AajAkVLRFqx0V+KQzZWYIJoWxhJDoVg3pw9XWTfvsTrgoBGRacmLYom9PVaLpqgZzCJPzZ1fcsgGX1Hrm60W4CzZao7oCI/mxxWQEsrla38VESEQnCsty45uH6fSVcjYBT5DtgUVQ58Bp0tRITS6J+pR5VdxLdn+rlyAzb/rfy4dAv/9/7uHrhBTxYxL4Ds8okX047J22vvh2jboQ4KfyYqtXKkHRSedejZAZlmPJX/2MOMi+pVPkAOw5Hu9f6rMyzJyaUPMIwrGv6maI9ahjH5nItbmhBszCZ1ivArkm+YgWoeBKB7C7R9fmFGyUsnq8hDWy4/wbPU+5luALc0fQjADGOslINj0/93XO6K7cdnrVALTT75Lrurlo6H/SbV4JaOAEFs1hTRNfISE3XFeBJ1sn412zI15A1dFWxmvbKZxmZja4=
  template:
    metadata:
      labels:
        app: beszel-agent
      name: beszel-agent-ssh
      namespace: beszel
    type: Opaque
