---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: beszel-agent-ssh
  namespace: beszel
spec:
  encryptedData:
    SSH_PUBLIC_KEY: AgAmnfO/XGR8DiGHO98dfIqDr+JvFT6leaMBw5d+pJ0qZOrNVW/YHSyIKmy2vkdfzxnC+Ef1DtiLVkGlTFkW5EdHYuP2Jr+MecHrkRVEmMJc4siPd1zZjdUC9gKUMJ6YeSP+ET7QuA0pNZsqv0dXRlhJDlde2gMW9oocc1J8oviNSipast0zU5be7IUZyVuckw0UYRIyh8A2EkgpsYATXmtbp7MQ+JBnPl6tBsT/rE3CIfFNQO/T/PKAtOw+iB0zdch6z7I8/L2yLyyIx6McVRygOjVNtmW3hggR+i1iVCx1KAVc9o0WC1rfThexmhbUvyE5VyoF6rCTRzqTdtgjuczpnCNqjTKL/Nw+RNhUFMSV/iQSNdgZspUkpbZ3NZK/9RySa4DLdDSW4ybhFIJeOlUHX+JCcXzxzZ4h/66TgmODeqKYjEs46IHfqsK+C413K44OfQfSE9WAwbz8quSq/1aZsMQgiDWImzdP+975vsmmvubY0PXfoqWEbrejTw+Lf71t+UtslS9ARYwTStH+YfYYk9JzoW9+/SHWcUDBGK0VqDehKtd9nIWnW8p7NB8Dx8jSduWqtUjDRWFHFpwTbOuAFGNhXtf8M8JTyH3v+A3Bz1fH/prthPJmd1bR7T+cKDA/OIfuHietxwmqUJhF05MBtiVl+MjWmlQzGMCngWEckh2nXmxdN48BqWEGK8LDi5x1sGrGBCgU2ugsLef6KJu5yOymqXwXqggnennwBcdLbnv6AQhUemOs3oqYXyjg1zTrL3lnt604zRi+T4Z2gwiX/IrynqEBAr6GEtI+XlqToQ==
    TOKEN: AgA72L/RTZ/voKFW6OwX54NPalNrDCRyTcNRK9jaqBYHVUwK48ga3qzrGwTULBGEOmrIFf6S/K4OKzYSPRJfMlfG7omGKS4ylrGzJafDKU6GFmJzCC+QBctho0IfNL7eAqXVRg5ABaUk0d/uDa82tv3kUkETlJAgwpd/BbUGH4TRVR9G+saekh8tZ2HQFdx676PKElQzterkjdJe4BeEdvxzAhL/D/Di1pEbw5p9DIwdTNnFaEvUwi3YOELc4HVzlsSr97+F6SdMBAY+Tuk6/i/grtH4LrwbpqZeqBCwxpqrnEfHOWiDJbz/Ho5PUnYDLc1HFS//FinT5dxLs49PBSjPUcl+zu3Y9gsbUsgWxCobnpgUWj+GZj//L9VCWzcuWaXFfvz5O5q1Y4Ajgluk4+j1sBdDTidDuXr6D0tljaJh9zzWaCGBElRVh0s6nCQ6FwTSGA13T1FQnu9p0WYhfq5u5n28xMOfefVJnzj9qx+exutBB82aBRADjRo9QRuO0h3C4CA8fUinEGXBsTmY0bw8e1xDlLYCvPUoicHWRqyTF2QVSunJi2o8gzU0k9ANbxZR00QqNPKr708kK7FNVkYr98kUZ2/ZhaZkfxYG13DoZ7SWz7QT3RN1L6izAlXNJWfOYCHp6ZPErQYr1I4pIDBlRxojsh6alyMDZJyD5xv4KV6k7p5mH13PrSWjATRXv3xirAFFOunBQPbbm8Sp0rJfBO8x5nnifN9Lr7baA8JyMAao3uQ=
  template:
    metadata:
      labels:
        app: beszel-agent
      name: beszel-agent-ssh
      namespace: beszel
    type: Opaque
