apiVersion: v1
kind: Service
metadata:
  name: beszel-hub
  namespace: beszel
  annotations:
    pangolin.io/expose: "true"
    pangolin.io/subdomain: "beszel"
    pangolin.io/auth: "true"
  labels:
    app: beszel-hub
spec:
  type: ClusterIP
  ports:
  - port: 8090
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: beszel-hub
