---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-adguard
  namespace: homepage
spec:
  encryptedData:
    password: AgDDjoc5ESb5RHepmHEwiJOErlMTQPRMQFB8nfLFAllaJL4Cvczlx6ZbXZBC9CLubBPRB4J6c+Juw5Jn2/1xvFnVkK0fRE/f/gDlD6XLb77G1J00drGafrFAqaaE3Gkkg1fva4YkmCa3vW0Th2p/q/uu/3icB7pegZoJVAvUQbeWYL99/EY3j3XGX4XHSsEt2XXnEER7iMiKJJcJx8AS8dsb2nwl8BSs4vgrKmcfn53ysMjiLKyGOaDdcb5CTYKE2NSjJk0MVS3Vq9cRhH7dg3zPIXWTcCwdHtEd1OzRSWimuZbfXzeurvY8o+84ccpLqtvEpXWN2YXvG7SM/jKGd4N/ToPHr92PZc3tg3MEN5hsbLaHYXXFZOdJNZvexidsSQaIzgb6j0OHHeMY6tdOQvxZ1TCkViismrLjdw/Nb/U1wjQ99rBw4oTPfXX38eci2Cw6D3ctbytD9Go51pR7fo3vI/JfYjEvt4Uo+HawMPrHwi8PmSaL+KFlhF/Wy7p8rvkgKC4r6h/GN2/igfm6EzVYqBC4b6zFRxenf5g9zWtRmg4Kij+/iK+Ayk45wQXFLOFo3foysZzyeN4dW0EZ4M5WCDx41Jdgr0JxKQpsv73RI6s4Ojd9KZwI1xUln8eWcHj+5TGXndZb9YXW3q9jJHeRizeE1+koSSWZObJQmKMLwvOOZGE2mRdJ2cdJGibJ5bxFBZh8LigtDlsD9AyPVxYDyR6sSQ==
    username: AgBZDdNTy5Qi9AZZjHY0pyznPfNr7QzRkmeoZtgULvsS65wkeysM8IRIea45fmvyjXDhJnc7ui/G5wn5kh3er+Kgie9//fVPBQbST6S0ZUm6R3zQ76ys7OQMXMEkCHJJViFNCaFODu4fpzEnRYm0BPcoAHNQ1HOd3fHRmchTv9BPDwMnhsvk/MMNziAhR68FjMcPPUFrIjaoBKKEYXRingJVuBj4WzPllVkQlJMkajz0IpcIj/ApjoO9hKqGPoCG4elDdBynkCxdEMJ4ZOnOAZkxyCah0oqgSHqAyo/XCi3HOLFPbCqLKZ8lZRGvSylzqtoMnDf5Db0iGSrFvT9rLrIlkMWEv1XYyrCU7gxq9wMP2TgIFafOP9lrjeBXKkZkgX62mZtcU+LMToIs2i8GC2UQwcYPgEvN87S5q3DccDIXa+sKeYKKp0WL+Jliv5I9qmFD5SdNFHtwHAqjR41+wXr3X3G3FF/VLjO60mUi7WitftJ4vefkWvhEiIXCNorQq57Vzfr0/5HX0Ro/uYDfgruqgnnADfuzNojA8QVcdPrCNnF6LrkMegOr1JmBPtdUEWjQrs4rNK5Pkg+GCTT7gBqnXv8l5gqv85PX8ixRjPAYH4fIWa6N/MSkDeoRSaXPQUvUTi21I8epxFRy/bLYfwVMmRuvtHTooG+DKX83b4JUQzD/19o3OVCDQHJtV+OZjNJqAb8G
  template:
    metadata:
      name: homepage-adguard
      namespace: homepage
    type: Opaque
