---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-adguard
  namespace: homepage
spec:
  encryptedData:
    password: AgBNOg8Se/hL5KVXR+5DgkQ9PD7Mo7hbFVe2iHjAvsIPcp+C7cXILMqtQ2C3U8ekd6r1NcSWWEL8a+O6VpdkX+reCMDra1aXT1xidr6imD1NdD1xVmre1OAYsH2wBSfwiMaRC0cGYTePxJjbT7+F7oh1gQ4uUnkb5oEzV/cfjvYylAt8loROz53vOIlu0zrhJt0zMZ+uY0H4MKUqduGbwOYQm02ZJGkMuPRko+nvvw//oB6lV4yM4GHZ2QT/QNPFJDUqVZEzeGmSp+jA5sZxcPT4QxgMRePwl8cg63FOmxR3UVjM36aMPnirxJ6PL8yrIDH0C3JPBRsWCW123uHGue7UCL/tUK++flL67a8K3dNY2E7BG/N0Iq3rmYrmrFF2EeCi+pBtPw0+UqOJCKetLOJZuNgaUAfyS8+1MGdrxZ9mTXWU6df9htI1r/+cu0hBwkykYPkMC9Uu50+UGnZBc5oKBjKO70XPQpDRn55jJu0Dm3MzqUXLkmdhdhOht8Wyn8nY5lhyHFiuztue/iza9lEd/yU6bSE94GAgyzJ7HaaZLQIl3EJD9/lFgC34353/FLmSA9Ou0PyglfEMQow9YIp90O1ac+/V/7sOqxDhciBQM/gmP4k6p4AqAwRv5dcxqrUTjCPNzFoM9Q3sS7qhM9eOfJlb7nEOHL/1dUkcXRwwrw+S4Q1LCOSIIG1lsq2Y184loft/faypunHAES4gwm0eYZHSbw==
    username: AgB7KPvQ9Vp5Pp2TSTtEABptykhvyrm8sAN0Iawj6h20kr8IMMvDO/ZYO2Oi4NqpFV2xW2Y4r12KoBxH8B1QxWKUeEMvGSkPd5l5Ik7ceMtzijYbW9c3w98Boq353TfoLJOjowsHSxbvIjPGjVFJECq5hNbedyV7cLo0EoqCYjFb2yUkKoXyek+m/UcI8JHNwp1LvuMnub1Anrj8KE+2ACGnbTT9bop1UfDKEtwL9tN8nfVwlpad9+gPt5DypbGBzpMjWYf1HsMtJh9eTtXcPw9wr98lOdpAmSeLtBghZfGUXhMtKwkPUGQepwVcWfJCLsPqdMfdcdrCfGAnVbhHP9iMysEgPM1WYzatstfY1AXHucBP6DIve3tX9KmeNLYTgbc7OJRJ7z2MR5HpMP+EsovuChAx4+WGUY+wNuB935DTEMBZzI7H/fY7UoBQgl5kuY6wHfb/phApu1vYCndvKrR0XpqC8//Se3GJsaob2bHeN885MYzOuqRhwM3XXnwSwg5Aqck3JlxfGs26b3Z4wzCpLJ+PNnrTQ1tH0dGzHc1lQi/VLssmF7A8Tb9xqYwANmCfJnuaKr+riS2MxY/tI6REnbUZHAD2BVTvIKM6pwSxZ5ibWL2T4Yhw0gquuCIIwcuoQmesCXKRSYH/hC0OODB7MistdhWvqPspzHiPFzCOgZccANzLr1iJEeqAYnO04/bgosv6
  template:
    metadata:
      name: homepage-adguard
      namespace: homepage
    type: Opaque
