---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-homepage-token
  namespace: homepage
spec:
  encryptedData:
    token: AgC1PPqeZPzJoThHPEqAW/46W6jPKqoES/Bsc2Rrg1iQz7sMgS9oSNplPoI1EDy2YWGRQzfvnMLhGZHx8RWLkh9brym9Os6RsEEh8R+Uh1Vxo60kIm7wKIy22tXh4fmZjtwumwinXrlcycEzcvsFhUaLJ8LpXOEMT/6egVZVAnbxjdG0mP1h/5cBYTcvWs2arjxBc+nVMCmcae9AHshTmxmTyxdDOajhNoA+RxgwQ3S3ZNYO8pAFfU8lWHPJDREXO6ktcvUEQC8PXwYCEVIuvUoX/cZIUM+v/7uQn4eu1fQ4Y76uhgQXSGwhjuaZAt70gD78JOa919R0aOkrGK8uSeGRFBpxcispjLkqTWRPu4etCYjwHtNjrzL0GAk5GcxIz7PpZvghTLMlFr3XAzqUj0TlOhXogMzznX6kmmdWwWqC3dpyoIcW5UcO29sr54d1Bk3sk1h6uugJA6hdolVh1zgk2YvcS3tQ3Q6fLHJzWAEysYG/uWP7TgPesZdv14HJeGtOKdB63tmzGRKG2vX7dTYJTZBCatA6A3eczGr0xsmcK4GpzHPcHn59iS3rmvBISrkvkaf8x+Bh7DOL7/z11dhxradd9SWAjVNOT3XIBkVJ6dBTtyz5cFawSnnem7ZNcq8/kKAXN6nDSmnMpPXXopftKCEpNt3OH367c6Li6MR4uLcRW7IJ2ZPhwdmrj8xmTntNnlzoUxAzgGP9M52m/yxsScmeOaiCbLbFowHn4sMlWnPjwgXuIh7Ud+ExI5ENPlwsZeNiwVOd8cqNfW2abjpXPNJzK96Fp0ZT+4xS2IOMXVozyTVQf+8dTY4Iytleaftc2N7uMNu1yYdsW5SHtu2DlKlxeEq/b/jGvrbiTdgxXbD0CMgQqCkpPzNzZa9UeN+SUaRkWhyzzQ+L99htEvUKB9FfwOxidHATkwc1sW76ke4P4NCoqjDcPcix3KZ5AECYFIsH6ZdECQV6jmCMYdWBHWfnHGLvxEigd/3zexkLm37rI5opdy0g4iWA0733CQI=
  template:
    metadata:
      name: argocd-homepage-token
      namespace: homepage
    type: Opaque
