---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-homepage-token
  namespace: homepage
spec:
  encryptedData:
    token: AgCPw+fGI1uCIhweT7oBYJYr5ZJ+8YkCLD2wH48EKSFQoquqZk2PSr4xBo3lkgrvRDo2pw1Qbl2p2d0+cKQMQeAI4vKqX61Cz6SDJFzdU/2H25FWsn+r4juDtpe3LBLp+/IJFaeA5wc6QBKBIYoVXK70/vNGgtDW5S7ejtxPj3NEUkmzwyZE+SxBnUjO62NhDKGL4lUBprnBfMCwF/Xr2GNCfZgzddfrdwPjkLnK66u2569ZbldEHabOpmLuCoBJBTkan2qzO34RYBIzgjUN8TxB8DZhOR2waPcUTBiPpr1+TSP7NgUowdoGoXr1Fb4Hy1fmh6IU4mfCw8BmDMHsyDL5f+Y+vq3J1/HvHLqKsV2qOWLxt21KajA0WocZ3tueM7ew6r4qiHBn87yBPfQTT0oYwE3Nqdlg0qoBPV69qQQHZD7ycUjO73tC5cq6xiMSGdU3eYS1px8gBch0UyFQYBT2V8Ra1uusKoRIUjVqgWRrLkAzBTz07jU4Gz4nr6pAYzDkJcG1DDtrwpr1tBvV+rVENXg2GX+DPqiIQJhTI9TNOcFETa8+ZKMCvbgGC7tGlDElck/xUE+aeqFc2LnGCouAVWVvLYO9nkjPC8zBkMb6yM+H5nZkvqT8NFp8qsRA7aLgEysARB4kdsw5Ek4j0euERVDriAM4Akc6oIfThD7QgN6cFGmc509IcepnwruoWKlFCLwSvfWCBtk4luIojigenq0MOAZ5EnikO8LNPN78PGf5cxLdw/i2DJMFNLfQN5Zc/K8DXPA+86fws0M3ZocYpYd1LNIabFGVGrKkRcXSWnma7NYUJaWgRMldjpMu+GkM88FEmTU6LVjWVa2/DKxjPLsxAlRY15dHBuNfTUVhSCysk9aAr/IHTYfs1NAuMBgoxPkhUGe5nc8MniVTGKovWVZB2Fp0ODGxHVrTXF9+x9Ux3BInRt/dYHerjRjVS9OMRDPcfLTwefevsVWrWUwSLWYFC9qcmOuZkDdDiDTnGdMQFl9BKWuK1UADzLZlSnE=
  template:
    metadata:
      name: argocd-homepage-token
      namespace: homepage
    type: Opaque
