---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-beszel
  namespace: homepage
spec:
  encryptedData:
    password: AgBG0usJyr/qsiSqu5chWf+CLhYONFDVPyO8SaP1Zi3MLv4i+461YfdshLg6u5DabcU720r54q8bz/gpVRbXz9upaZpu+2DSfaiMF5Rm+Ozs2GMP28/Pg0vFwXIdDrLqq4XkFjdfMuD7dk6pzWSK2+PC+fviCEKMcfqyQRlUvwTCcko8qYPDcCMMyz4rHO1PxBbVAq3L0ev42OgyApPrx85WNICHjUj7SDFsWa3xjkl6NYWG0ulMkKpqGITcMACZ8ODMNvBdFM8FsEr67ttTNLEDG5Y4+iNWZSOBtAbVFRpkOOdwREiVzvmGKa2aWRxhing4efwvHYSQMEz9NPLf1pHraFgibeEfVUg69e24+ygDdNNIqvSgDvswM3PFRZyGfJqeMgOntBVZ1KYxLoVv/51npZidFMCvuvBamPEU8uxhZ0/kogYsVlRud8e6mQl7iamZCPTuzjoCTZGQUnHfuuy/j2vFk8BJIg4biicPeXnwt3t0o4qkVx8TYBXRPM2xJRKCxy63id5VqN4+g54LB1INCaibJVyYEqjAf4TDFhVOJiwBn8wFA4/PGZD7l086M9CHx+MIgnWzYKb6CwNpqD09qN4n2p2hL3YAMMqlQLglkkioA5zmkgUBgletqOBtyquUZ0SjTO+p5mkj+jgQC11m2NG4V6HJgA0Z7Gm8ewubpkF1qRUhfoo5cr0/zcHX+tBUSCi6+JK7O8KW8jGUVpsXXTeBuQ==
    username: AgBHmuc3H0aqmj0AYLnVFlGEspqjx+ugb5z7XS+C9mnmmU44xaNNuWnFa7ZzMNWIWc3QQLqQDAN9bFua0EEgBEKslroEma7TgbEV9XHlDvREOATFFvQlQfKW1vak+SJ9dDJrBFB3ShgQR8WxPWYcxCw2j6SvauYqpHRfeHG4nJklgMt3BNuuYcWpg2V/O+ZD8asyREqmeFygTyu2epCV3JoC2OfPaa+YxHIOSZv9uqq/Rt20jdfCVxJh26bK+k+///OFLRY4CVc8bOqufQGO9H5iJ3fB/4V5z25jeFH5e0+oljmFSrRQQZkZht7OV5YM20NEFGOnmddurgdqbAr0JVQkj/oTJ3jIz7YJzz7yXal8sHxlX/J0GrjIyt95ymuKCqAmIfyBLuLEBsQBZU1ift+2u5e76g5jfunp5Xtg/yxtO1SVA7zZEhC+b84v45Zr118hxr2CZr/hnyKKC34LVco14ffh2rj9mkCHcwn+OfZsQphNR5PsX1dfLPeUdwlDaj4DjDFXIzHhcdvqtzPLhvxbmxMKlyaVx7NffGGNyhtHY1dHKx/1Rg64LsvvaPYtl43Jmt5H2KSYuNajXrp7XLaLrywRLECdi0T1KSM+nwHlxxfA5sEYRbxTbmkZIFAgGUae2w/h0Q7Xp/WtQFJAKhi3FzMfxZmR10aHgh39iaqgg+X1ip0VoetBaXM94BbQWVx4oUhXJQ8jWFSSYDI4f6lAxgOZH0w=
  template:
    metadata:
      name: homepage-beszel
      namespace: homepage
    type: Opaque
