---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-grafana
  namespace: homepage
spec:
  encryptedData:
    password: AgAWP5uh6kQJpOOmUHWLDlEJFLfHqSQOCg5hLxDYSQ/DLkzEF+8qkMrxL6IhNBwlvrpyistGXi7uIcdht3eeDZFPQikRHqalf6ySEJPCQdczRVCYkBiSEzn/YBWYcJbK0YDS27EKZkWBWvtx9tQ4VtorYvmFoW5BTD0h7lozCTKKhSZQZMfBZaPLeZLfigD3gFDmZV2w8C7COf6ryW97HW5o7fijpPP/1xWhBIrxb9MCuqCehOWPVWpuQ61dOWFjH0xSmm3wZnj6sCKDX64h7pO0kVOpA0tjCLxyPOmdmfY5Xs0noUuNALMItIbTK2r10rox5AdVvcq39wvxDA+j7W+MZK3SPLW4Dl7NMVm1jjLueCnnvH2z3a7WZfssmI7OnGClPT/zejjA1o6giuzE/HcxliW1At+8DNkpEt5B1rM6uaoSnRpTrAPXQ9xkuNyEeRPRnPDOmFalE6HpDa/E6XdpynQfAkKk/yUbTYx245U7CzdDxvpq58Ygv9sCAjecwS1r2kU1uvFoJ7IItZlVGjiEKTwI6VEiuk3cQ7sdIU3afcMGwjIh88r8/CALwxS3y7mYVn5QwBLc1ER4rZCFTGXvqwhP8feS2A0hxtTtdzk//nKnq7lFElmG9iJbqjiEKaZj3pDwN11QBJTFu3ujkjUWUbW1ObVYO2VbgNUmLLp8vEuXwTQKTKNbtSBnWuH8fNNwmhdy3KP08MqBHHxvDQ/l8rQ9FAaaTQZlZKqTWFGe5b3U4eOVvaTOU3no6A==
    username: AgA/7j7zWJVNcuhISYxLbIWISu/a5FsN8wPo9e47cjbG2K+jera5YJ5j0ht+BQP2J+N4qUO54Y92CazXKqD32aK6EdbXy37gIbpkaieMeoREAOdcLL+cvlDBQa4A6NStofDRSMntqGiNVpiwfk93Hy98iECJsqD59j0CjlHfqH47GFYUQ/tm/d+INDT+U7gr37mDORqfzvDXUkPDWJx8/dXStBCbbpr0xW9F+UD05dMr04rK9uY9tRAWbIRASOe3z8sUdrE+txpbKo6ssJ4b+GTkWtIbPw8SIwMUlz+RrEQ+iDTo3hARk4WUA2AykAQEt7SLIAinFnKIXswwMmeEhrRYL+Kw3zLermpIcu/mxfJZg1LrDDajK94k6ng5i3Ys+c7yg83Eoqtd2UypQJ2p0VbRyTTmhigTjX8eoEP/0GfHC7ltyrPtWosQWUCx23cKIuxLlzo0akPgdEJFQKO47eDLEVXiIcOC6C3cq9QLcZjkx2Yk86+lPldY1d2EdiW3ptIISreZiPMwP0OE1A94emtA6KumHVjDMjnV0hZkj8xLPAodVVydAJgZpJnX782gtKGuakjrSil1mqf7wlp9P0SxtxIuCsrkIvaf9W3zt1R9aHuNW2Vds2GbQKZGG5ClRcG9E8mGj8Fv/O/LOyojE31IC9ZRNhXIfpQAQlEnCJXQckGjGIrg+OVfDsyBXf4n23xMUw76WA==
  template:
    metadata:
      name: homepage-grafana
      namespace: homepage
    type: Opaque
