---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-grafana
  namespace: homepage
spec:
  encryptedData:
    password: AgCg4Ed/fAQFx9KzEno31mlC613jE2sjkT87Jp09caqMIInVFq/i48qkmjBcCqeFI7pgQrz9VxE1Sq6K6QJn/p5/P4AxF6Pk64+Dt8edn/mbLCZjrf3koj5bdzdgHHDzlK0TaNHaym31U8ZCDbnknQx/BLpLR7SdLCp1XSrHoJlPdwYzDKg81hKVoVKCI0J8XeBUGYzzjT5hcqfKaf8W6qAm6oMDuXcVs06PyizzFwPT/19G+tq4YPn9opC5J+1gUwKje1yHCRYAZj5vdG7oZF9K2pbUpAYZWQxPVq0m7s/Yo3E70NohmQ77ehLTx3YW67DQ/Y02nrj/qSowzhlPzBd7wU190EwFCqR/pHLnVHUSeWOMPU2M6WoSCpJHXfDeIHURGqTjXnLWST1TAOFB6BVp8yZ9RjL3aPK2aJyAwA0B3yy7I+5asuqXzYTr2if3r6jGbUQqjGr0+eHNiwocI2LTxzNpp8b2RlLQu/0XlpkFgWV+pNXIYLlV4mrBlAGXSlNEFH+HZJj5BbP9ChNHM8+FSWKZ82mdW4DPEE9ed61HmINJpDIPvxiFO/wib1HQP+hlcEFyOhgcwLuzJhgi+eoZXmVCEra8vpU9uqgTW4nqBaJPnS8BPWhdhQ7cxvnlmYgNKG6weroQ06+rU8cr0P9/czaVkC886xE+8oPVuTee3eJ1zZapfdVQsNKtCWRYD5CGZ0shMG73AWvyfsUGZfeLAkDsFH5SD58uUcdqQ4YjFJqScIyA1zapNaNmfw==
    username: AgC45al3eHrnLMKEX7KnZ3qzocbymJzss/gUYslIGxqrYFW/b8zt9onF6DEFtWE1amVwwbge8epaHkNprnxh4p4fsUSs3rCHzuqzQWPDknc6S6hSjVsQbYrAeTwyRtFg7Kudsr/gjcS6z4rqqRtjuBQqhUSpYZb9rWY1Za2SonOV774TATK9DIfyJy+hmF53evdUzAksLfAo0ETWDYMEizbMwIMCp1WhA9hYBqTyJ2G7VMrFOO9rRw87MvwH9xBgtcXpr7qEzKYDEH3cQDJHTdC+JiCFehXhScF914hlUHios70ZNBkhO3KXEwk4RN/+CG7XJ/WpK0kYWzAXDpvV+qQ2ZPVx2Yl6R1itUH5OYAVIxh61kfF1KL0YMIF277jChiF1zHQb9gShD1Svet1j0u7fVPiNPOQr8vvUN6mA5dIv8od0ZG0DhcGRyuBN7+XNmVhnY2Ejr09TvNDpx0ly/kBlQa7xZJSuZ+QzWuCGU7s9tARgYMPM3835/YQutvoHRw6yD4thViTovIy72eCh0mDj/+GsXQZKu//htS52XloAvkn73OXpanrY1g/tbsq3s3PugD6+wGL6WBwifypiiiD6+1miL/JYT//zktuNI2CPwNFhHT0zhB82gv1p4p4o+zh0JRvMFrXERJzS8M8ojwxhUTVDdI10dgYU+yJOmTkfnYFp1T4O29HTwO9SS8HuXP6nTz1WHQ==
  template:
    metadata:
      name: homepage-grafana
      namespace: homepage
    type: Opaque
