apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homepage

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml
  - internal-ca-copy.yaml
  - proxmox-secret-sealed.yaml
  - argocd-token-secret-sealed.yaml
  - adguard-credentials-sealed.yaml
  - portainer-token-sealed.yaml
  - unifi-token-sealed.yaml
  - grafana-credentials-sealed.yaml
  - plex-token-sealed.yaml
  - nextcloud-token-sealed.yaml
