---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-nextcloud
  namespace: homepage
spec:
  encryptedData:
    password: AgCniO+N8kOSYR3eCr18xzrjGCNpFtuyN4OR4SyOYCIIzAc1ONTOIUoHbRmDdcw7/1Yhbdr8g2i3WMfgDZJBcgmKr4Ezlzo92ArBQNXvB/9s6nmEtzaMvF/UdXbgFxvcBE6duT9aJsEi/e7gkb9v4IF1up9lGJ73v7B2CCO7ZCGQHUZOo2aanCOw/lNLX6N0ekKTRK8jFJZAZm4duyhMWTMzdwRfdMh4rt9npZqVGNok5XmYRW6itk09kX8xdlzTaFK1dUmGBzQph74A16XWlwOq4PYPTGMwKWHNzTsr76QtgJfXnAjckbKqVYdTaD+RDurz9Z1RUaZfGI2P7U1D1G796w2PvCFp445pDMAuDGXuAhzom6jWfggS8hC1Tkx+ZxzRd2n94lkN1SC/39ImV+FfKjBhyVNZTVU4N0U/zEK6LN8X/cIffVgIAIMo6OVbIYcoN4LPa/NPOUpKjCEPqabDBICUatHF3+3ye7KGWEMdN7HeJgQMl4qIF2Iv5wKP39wT9ms1rYpZ72IEdSvkgXx6unGxkRWohBsM1LaibofO5cvAQBukA2quuJ0BmWxA77OC5HkFEIj5NxGeLpu5HUXGO4SZeswxd7KBYDOCipJ8sQFXMnk0f7mR9/++wG5ItptXBmfGmDgwOVuszl2JkJEf2tCV4PdXJYRjv+rJZEp6pxXpqbDONLyDVhYItDgolRdLWsuxHHbdu7UQ1PrCRRNvBqbDgKqQuEkwtg2BMg==
    username: AgAHi2DWRjdeZaT89vLYSxLI64OxjU+0PxU5HrEgaoDO+mqalOp6ZZQkiReEb0psas0mDuF45FQyCdPDAmmYngdSVJBjrjfa2FN12VUbJlAANP5J8Ud0OdpROFlQXW1EX+f0++dMBPR/aMvfRqAZJgwomv5/u0ETsAmsBEOJ0IFySnptS2msOiC7uxfL6pl1fh+S31aFP+aGlWII0HTSApT3Gved/iVeeTC/m2cJluHKnqcsu1Fq7ROhFl/zsioiDJt6TpGCV7kLWoROTEMNNZRMIMN1UOaU8jupIh8iqVf1i+NfHnIT8Ky32KVW7UWW5ZMXFSpzbi8UD3sR06Qih84vlogYGKUkV6gi8ciw9C9pZW7+1F31xmFwyhVTV8IifbNfq0m/X+WNwPm+4TTB+4ylhTzQI+quN/2FBl7VKXlKA9jNHMA2nqFMAqukLfpbY+a++YgkA20bGGntgGTNdXiilwx1TUsrZ4M2Xho4TP1R/RP5a3yx1+gMAZZdR00DFa9x8ZS31vm+NR7pFJaV2mG80XEkcsUmCt/KLVC1obAygtbwBAHy0lP5D2DFKiXppLz5YbP/s0pN6s7HLVM+bcwgVm3H/vBXO87et8NgWSYsvbC0BbTk1dP9X84B5n/Ra96098mxATSnp1Zejkm10o/I/S/jZ8BcJ4uccRuyaYKcxbTEBJJeoQHttHp6SZFiGfGBFSvkTQ==
  template:
    metadata:
      name: homepage-nextcloud
      namespace: homepage
    type: Opaque
