---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-nextcloud
  namespace: homepage
spec:
  encryptedData:
    password: AgC5uGyYpLKc0rELc6748G/jzn8Ds00k47Y4xtsX1z7ETHGXdyl61Ek41COvWPk5LdxJ1u39NAlWdDAk8vgDRdRjGPOv/4yCoBaGebR24Qe/UVBhCOlXLjEf8f5vyhAyMSDDVbD+UdCo6gr7DrnfvSQk/luwpaxAJ5fr4k/A47VDr4lNbsgmVaBO+EFBOOUb/5rVbO2/5g0rrIj4xOKUVemT5dzzxl6eB7MozzvLsKKdKT1o8oI2PBna/jC/0S78+8SJtDDU7r8G9makG6vkXzEusVb/WRP+WdDsb/EdSHzXua/52LxTFvtkW5zvzewbFdOQpngQ5+vtyqsfVQqnpD1XsP5zX19ysDf/BLMYxFInUw8APWRvHX0a50Naycu7smmiz/CpbJRMXCHHIgoMPXmBi2q+mJ4uJU88IH9BaVIKtK79pNMyJfotq0SXpSBkSbRoBCKqqx4ENnC0zZonjIk7vS5byaiRvbP1bfFrs+iQXAqbv4jJ1iTMXl4BPtpvb0yA87QVIil37BmqkLw4A6erV8zH/Nhe1N8sfVkWIdGZ8VqO8FGqF5RymSm6UUllVfg36ldiZh1haHjw0S6a2R7Y1Y9RDrF18eDM/UgqqAnK9hRLxPnuGZCTAELPnhylmZe4sqSs7Y+bnTRpnn7pX2e4EpHNjZs2P8ZtIn6jyAK0fXS7AaxC8JKzO9aAfNWwJbS1E336RP6A6fM8y4mkz9dbuz1V/56MCJW0Pe5Gjw==
    username: AgA70e/2CpVno9BtqL/WAmN/WNum1RBY3BGuGQacNjxAKN4Zl6LwkIiTmz3ScPPeKgKy8f2UcXbjcj4MVbhJyPu2XcsEVq8LB4rQoLpgS5/otr2aprXTi/Qazkm4l4zQ/nd7kKtrtbqdsVMFxuhRoShzxr5Lr1OTW9H5l4Ga7dFaFyjW59MykOk5YS9ZidwMjC9HuOFIAJ70uZJbbgNrVJwxU73/7FfU0jJcNTCkwy1Vp41tEEyCrGFBbpZY7B3zFZ/Jwv+eYh1QyAUHEGwvm/pLM4kcHntbbLhOTg+OAc/jCivCBxnRvvn1XdZbfBNINaVlJN9jwdu6sujT17J544RX0D+A1tZNzwIXOaUV1M/0/fF8W3kjd7ETcxopPW0svB8EIYGRYTdDKAnP1atlagrCRGOhLx4fReNyMvaj4PrLUXqna2PptB/fgU3lj14obBXxOhjwZOOirsCf4tdBjZEeQgA6mYVndf808DF75peHs9RQ7ngGAyL1b8PxrZUWOaMyAAN1oEccaF8SnZdxRhCUjPdJYfehoq+YVs3E6PQakfSHxcV1yKJbJ7D+vQsLZ9Cm7RRmdEroWhKcXjaTfib7Qg51A7KwRsPMvuZnvDaAbZ1Pko9wRJhhBzLj/z++6uwScDUsMs1jj2tNR3E8Vse1+0JlM4+NQX3oiWix+N3ZKL9yWDTLMEkqrprzPaLho138bnx0rA==
  template:
    metadata:
      name: homepage-nextcloud
      namespace: homepage
    type: Opaque
