---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-plex
  namespace: homepage
spec:
  encryptedData:
    token: AgCrvIzjOutqoi46ZrTWUa2hexw4zd8FjIfTsPQ9HAor5RBcq/LXSmn3b0vllgvdmrNbKIYY7At63kqDVJ35TkfmHEAZ44lAxAw07djqmyjIFw96VS7nqT+NsnZk3n9ctj5sbq5TT4kORyFPimFTdrCtKDK6PVkJKCDgPzDLTBCZWw4o2/EwJjTmMCNOoDHpXruHsm2W7mmxSslTcBvqKJElDfyiu3sMkBZzvdCd2gYrmU68s/hyfgmRoOjgItKtO2kGGadpa/lftmJPX638oWlNKZeWAiff70hvPbfrHSHtoZCtdE5JJhnw8Ldjh7yFOVQ5xOigaZIDXQCDL64MAO0xqmLjepIUj6Z0gYdkRcmxYDFUPnZq85P9BFJhgnJ7uAs9lxuewM+/TpZ26NnHcRiubol+DDISqjBWHSqsVlrFRvegzip3C7FJD0sLzDJeWb8s/LPDXwQYuP/L1q8zjzIj4T8C8lWXklHzYRmw8M/1GkVbws0uXgZeu1Hy/N4WRLw21SbABnGfgh9hC+uxjrTGL57Bg1fLZP4J8Ew8Mjsh7HMFE53h1QrZo+NYfKT/oDowKz7k1dKxguIUAXMHBVdN/ViaC/LtI9Ev9qt/Bb90biFzC29abzpiM+PfA+oqOnicTjGWHJGdC1XpTNcLz+0kFi0cSwdRAEJOJM05O2UP1Cj0O8Kz340LJj05o5itTZipUNqmZYMP2OZCXJ8xH6rddlDoyQ==
  template:
    metadata:
      name: homepage-plex
      namespace: homepage
    type: Opaque
