---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-portainer
  namespace: homepage
spec:
  encryptedData:
    token: AgCORJmMW86BDwmgztF9vVhhqHsRaHVj0MLbTPW4sc+T9r27xtf5s+zJKISArgaJn+bH2pNO73+yalHYKaz66coaA4ARNrsao1jclK5xJemKkVGCIOKioPUtA1Ut6LMXXzzBan2fC5KW35jvN++gH97Nk+rGyR2Jl0Xi1a/S8b3e4P8+1R7EKgUHxg5K3Lq1WyX/xFRsFCWpW6kf7PZxsrVuP6EX6o7W72YsOfIkaDg/5/RkkuwKrKotaBUK5PxuDr6ZWMDAp+Rtii134NShORxAdUYIuOltVe8Yd5P/DF3FcKQS4JqnC7JFYEWCk3/XD+FpiRWcII0piD9V97G4uadiLRxrK7X05hprx6VLkmNNJJe2lnnBYb89brpQEt+T6mb7R0yr9Tx+AasIMn7gIEd0vfyGW6AruuLT++WbQX3lIBezZScHfg7JM5ITsO/LGg9SKm2cKDUXytUiT/ROANnC4cLKkOx5Y8IwACGdPOBL6RvwFiF5fqj0RMczvz6mVuO4603/Mr1SJ3Ed6PYCmEtf1LVYPHWGCHbQPkxaK/iwo0uW5+YnOvTG6s+4H0MxclLW9cZOrtl9tDEkQa2wnCO+tVw8w89wQ8/qsO13wRocDoKvOfGqADS9l3+dTTZrOuFkzHjNEDOIAsz7nbKiqMxRgoLcBY4Q02qWEsGkItYh4xYAd8m4JQI8+sZhiJu2IJN6fw9QjeNu7eKgyNGQqY7SOt5ldRIxWk37R1hIg75SeVm9rj1imrEHhNxqBo8Nb34=
  template:
    metadata:
      name: homepage-portainer
      namespace: homepage
    type: Opaque
