---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-portainer
  namespace: homepage
spec:
  encryptedData:
    token: AgCO8g2zoyeDDw3Krlo25qIuhDhaZF+9aAwgByZt0utL2zF/6iQjyRzO3zN+rVLAqS9rLUBhW6rFvYNApn6c6rW7sASGp63RF25yJyRS26b0LIZDwLfN1vCwX6kVZqPFI+5QcKT8+UZ7v4HJpVOzerupWe7v7uuEcWxrYz8i2eBshqicpy2CPLoW9DOAgKAarWo+kFMX9SZLx2o3IWpLVxpSzB6anxCpgAODy1WJ2zA/eP6BNzUmR4o0MDHdQBex69oXY8FkYS+lBivye7rg0p1ItgFfy/2V8oMYh8E72iiNvvqgmUGodZZqUSVRIyGF+Y8FnPyWfhB+2mFJgYYabXlx3/IKN2y306X7CzPLpgXxs1XY+8YgMTXedn+CAt84DpB8iTlWEEH+0AfGY9XDxMio3AzYXYfh+AA2q1r8957Mu7m95iPtIg7ApUHVPeoMTHbQDbru/8BIuExoChGe2p+gUYuV/gnOQV0aneGQSqUOoC9rdyRRS/+7XaCtsU/stD6nwy8g7abQsHfDrrwSW56mfnkdgwProhZjHCkTLa3enrOoMFYY7cVfFtRgtLxMWA98tq5bkcONWbgChWPjdh26nYWutmAlAocHdgkIXBZ0/irTDgmunv2L/WNa0vyyFIwFcf5iPQ7kU0yQcy1IPy/Dx+aOd1SXG5TBDs9EHU7IAZHtjWznBr4vVi4zA5K/eDYLuqjMKDJBbooGTrPHdZpgM13+MAGaRM89pqJnDGDcj6vu6s5hp7IpMjvBxqDnY4U=
  template:
    metadata:
      name: homepage-portainer
      namespace: homepage
    type: Opaque
