---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-proxmox
  namespace: homepage
spec:
  encryptedData:
    password: AgDEAJFFrfvH/QKsOnjFOwJAQcViXSrJMaUGEI5AdKEcJpmxALViY2bQhYpAchL9SBmP6t7qSjsoVUGy/nXRdVZc+ttAKnIy9Pbl51BQ7oLLvCz3ixyw+4j9qbhmPNc0zTyGYfcTQoe/JNLkcnxSxNUuvneCQOxD37Ya/LggA2ykv3VYkrZD9a00sgUyCwU7OCItsNjiKkpMsNwJnSqFDMdBEz406slAgJKDqkq2d2HqCOwQvqcPOzsxLDaVx87/Wn1xMPpf3oeKLl7EjyEMON5UALdUPeG6Zvt8KRB0OWsOcbw4AUPUPEtFMiYz3Wp6VytlfSiDiascs9aYJWWVIDT3BeQpsHLTyt5g3qQ3ilb1uEeWfneqbpxoykSms4f/kontx2AT6654NfY4CNqVy108Q+qAkJhmFDWFDT5uj42QTHuDrO56hmtj/cG+wZsgQW3ip2TzqI8CJnijXsJyuhiv/JnWzK8sdH9DUo4FzLmR1PcS1hiPqIxcH9sF69BvkRIsjbTL6zPw4xHsE6QZkSV3thN9PQM18TWYrAYSVqCEk6cYhzNWXKFxtyiie1QdUtDzePxlmeE8tEgxzGMZipkC7vrQE6pprdE94eZCPvbW3cO7EXJAc76s7KxjQIw9IuLXMCHmGjM7sCBixQ4kJme7F0+h0dcNoempaVtjE8wjq2GAdQlLyt57qCRGHSuBOyFpxyhRhRq8aaxnnHAOcPWKhjPVUaoGcX8+j0VEafE9Fk7B6mQ=
    username: AgBX7uSv2tyQhqeKu8Dje81VeYswA35iSpGIkofxiM5PJnV69MbEncptIlb9uXwGbWDhs6ZNKV8JJoFZCn5YsYtESXq6HrJXrWX5hvNnzy9xMloKRQc32F1fXpOi0HBTPi38Pc4i01zSoW5MvKR21WsCKTFU5txIMu4oheYu3Qx6epph1WNhR1qNjym1fBXbvyZ1bi90GMLDMCZv/sOaKHHyp5+4PZeEhGVOttRbbcMG7BiQM6jpzjWQW0OwcUxGfLjxRW0rkx0SZCvIDbvfaB+jcZvRucSo5ODke4C2bMP6hMlO79PLpY4x7ry3A99sLc0OCP7WBktzQuga2xkI+z0htd8fj66fctqiBtlI40B1/mElaNilOJHQqOVgFvg3MN3+AI7vf1lsm2zVc1fsi2u4c9x3E+VAeRSP/SEkffeqUxTlhrGIdAvb5khKN7+XUjHFFjGQy8ieImv0Lz97N5zu7UAjVzCWJ+krG+ALSirqhGMRAt/bphyUM67QVwMBSmQ6foZdqe1E/9OhI2fdoVFtz7TUT83UGKbQw2VryOGFZHZw60GCgDtiEA2XPZfPtT4cpaF8Sl+7cIppK+6lvVJTdmWkEeaDgn5POgyDB20WXsJLrmKiiEpam0ROgHuU3FJgV+2KhdnJNJ4L5lnKBC51C0soJaXLDuww7xK00ERZPCzyxy3OQ6s0vbEfbMaLKbc5FtMjr2d4BXxsKeO1fNPXZYB1AXQx4g==
  template:
    metadata:
      name: homepage-proxmox
      namespace: homepage
    type: Opaque
