---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-unifi
  namespace: homepage
spec:
  encryptedData:
    password: AgAP8YRR/JyJcgZbBhpiAYRJ/o3i2MCwMoE6vLgd3+W7lYMOuCICXhJCR9j9YjRaEOWlh+igp+td8frMnTSN1E7w48oCLE2wYLsZeMqrLjbmczNZgE/gQ5eg4nMURZEbLcEJFg460ynOthiorQJLk71sVI7gbNKbXQ+NxdhnjpZF1HQzUTTafqwklxN8z1Zu3OzPM9d1a8SYKroB49YdjYblEeJDiioAl5ZVlA5fe4WeHeNnP7zIWqD/PbIJxrD4OXhiM4CMfoMURcQWmYVBBoycG0FJwvfsZr6PZYJs+5MpfYunaYXD3HH/AYBkgH7JOhNgX3B3AQvghuWCAVVvp0eiUtqC1EhZOGsqvp+7x0VSgW8I0ASLqgDBnjAtn76rX5M+sN/2xtsw2KnXPte/nEZSi0ipTvFShEV1KSODQF6S3+x/aQTQEcymU1I1CFnizgOQPn9gPemMO4b1LwPt0RM/RI6ok5MFu5ymq/Gi2YO3Kk3Rr6lsBAw8BBE3udxSwvU80TWaIC1XkAtSyquzi3gzn00CBnPvROk17gpwf29MbIOQwmJbE/sCAL/3v9PSqwYh3Nl798U7WPTVkEoU9oKIWYe7EOlx7SIvoXheiUUeMYILlTri2WHJcSFZEKJrj6nrsxJoBUVAFsj095A5xokQ1CaXNIo4v7/JLhpMLg66ynQaNOj5EDlCsQF7l9DDy0M/J3Lvn8J7Qoun/3UvjwFHoipAyA==
    username: AgBM9b/xA11t31vKS+Dh3ZWbsem9soRgtsGBIiW7MhM923m2tt8WqGQ/vloFB4xv4z0eeUExgE/S2Pt6C4WWNL3L/Ezd5SIag3laENguLhEda8q61i7xWpbgar74+hekT1GDZ/ZhYzgVwFLbAuhC/hiUKfEhhDQ/F7sd4OsSL9L0HFlOFqoMPpjx7zJGVJORcnOZtkE8mlG/5cyCQE55ljkRRZd9C/mcb+D8o8dwDBgmKYIX/J1cbrrlNdGsYlq/gdvKclKR6ULQK6POetZOcWaW4jxFUNWi+lPqJs8PzptwMBuKEklp4VdOs7lLGIdcgS7/QO9+vyfSxysgyxeCu7J0WPMoVgx5tsGLRSa6elE9UbuigEo5mUcSajCr9RrlSVo8Od2C2jtcCTnpmyBCEhBjTc9eSlWRNlHLSiAJGyEEgPfzY1BQSDbumR3dA07/uLMf9rDXIccAVGhrq+dW33fLKqW5uSsX7Gnp/yGbG7oQR8YzjMeNZ6YsBoN5JY2ZJX9xkniQf4MiGC5VVwujzDNvexZUqYcaNgUsCv0LQ8rWdAoAxYymQk8EskSrXllP73Vt1hBdWF15Q9RdjRIYdwzf7f/CpgeoQ/ZlkmYAM5dJ+/52Q3TOHWm9vUoqv1YVp5+PqU/UUXWmZGC8EV7dvAUOp7a/o5w+NjkicR78vgcFlifBU7GXwleB+NYAf96X519YvtUtfbqUCw==
  template:
    metadata:
      name: homepage-unifi
      namespace: homepage
    type: Opaque
