apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nfs-storage

resources:
  - namespace.yaml

helmCharts:
  - name: nfs-subdir-external-provisioner
    repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    version: 4.0.18
    releaseName: nfs-provisioner
    namespace: nfs-storage
    valuesFile: values.yaml
