apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - cluster-issuer.yaml
  - cloudflare-token-sealed.yaml
  - cloudflare-dns-sync-configmap.yaml
  - cloudflare-dns-sync-rbac.yaml
  - cloudflare-dns-sync-controller.yaml
