---
# Rewrite webfinger and nodeinfo to Nextcloud index.php handlers without using server snippets
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-wellknown-rewrite
  namespace: nextcloud
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /index.php/$1
spec:
  ingressClassName: nginx
  rules:
    - host: nextcloud.elmstreet79.de
      http:
        paths:
          - path: /.well-known/(webfinger|nodeinfo)
            pathType: ImplementationSpecific
            backend:
              service:
                name: nextcloud
                port:
                  number: 8080
