---
# IngressRoute f√ºr Traefik (mit selbstsigniertem Cert vom Portainer)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  namespace: portainer
  annotations:
    cloudflare.io/proxied: "false"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Portainer"
    gethomepage.dev/description: "Container Management"
    gethomepage.dev/group: "Management"
    gethomepage.dev/icon: "portainer.png"
    gethomepage.dev/weight: "20"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.elmstreet79.de`)
      kind: Rule
      services:
        - name: portainer
          port: 9443
          scheme: https
          serversTransport: insecure-transport
  tls: {}
