---
apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: portainer
  annotations:
    pangolin.io/expose: "true"
    pangolin.io/subdomain: "portainer"
    pangolin.io/auth: "true"
    pangolin.io/port: "9443"
