apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  namespace: n8n
  annotations:
    pangolin.io/expose: "true"
    pangolin.io/auth: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "n8n"
    gethomepage.dev/description: "Workflow Automation"
    gethomepage.dev/group: "Automation"
    gethomepage.dev/icon: "n8n.png"
    gethomepage.dev/weight: "30"
spec:
  ingressClassName: traefik
  rules:
    - host: n8n.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 80
