---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secrets
  namespace: n8n
spec:
  encryptedData:
    db-password: AgAo/qPPHTS/JRtCX/kJRGXf1w04r2X1I82RdHVgQrJS8NZ+WSys17hwJLtORnvX8hLcHTwRUrgzz/rv9T0XVOYurkBpyALMmT72aNW+2Tixl0hTnmsJnNAsuyluqx/qkM1AG1uNmfOC0vx2cnyTOv4/W/nU3UkcSiKEDQilmU+32iHJJ9FG3Ey6RU0s2glz4jZexn03T+ewkpRnUGoz5F4dARz/rOKrH/zDXQeqCkFUYvBKBwpxAl5hZf0wrwWsxNYcAwctj0d5+BXehiNgPzGjjVrlxAA2QSqyQ6iHKnsaEu8isXiwmueT0RZ3Kj687tS+PX8chy6RPVCxERMStf4KVcERHez42ab/dLWwCeYpsgzoWtqjLRVx7KEc6dZ0MoTZwBtg8MKDt6m8qwwrcGjIJYBgwxd9UAdWBU4wXN9zvJC408KWwpd2nXRbr6c4PYFyuaVBSDarU7YA8lhijq29e6D1Y8J5vYueCyM5tLsBJbV+nCUjAb10vEo4f2S1xAyDs7D3P+tEkmDCOw7NEIMDJQAy4IyjNeTqGCeTUdxCKH9mjGw/AirVsGonkMeWAQILpxljLyHvTrZxciabci8iPONvKJXfQ0ss2nts8vXJuH2NfjEkUB4Jmx+oiOSZggKNCgPHV79XFM3RukeXOhJ6UOG24JpbTEQY7EiETvmvD1kIhysGqoH239k9afnWbgWuFRSjrUG5RjUIBrwn0qDMtTP0XsQOFGIjokgntR9a2r782KHrE65OBXYkMg==
    encryption-key: AgA56WXxzZQNSXTEU7RHCSQK0ImSjnT1d9t+bk3R46jKYhJZfwKkSM2A8YOccoHEkFdY0c8FS7B93Ds1jjaR47DtC/bKKmhBpIKYES3Wn4fD4dxOh+dcDbILRozIdpsS6hI0A+mpxOyawsgWDrzG1Ip0OjzwR51krUlDWcduClminOTADw7njDoJw+71//12hiW0fJX9X2iQNlZke9Tgb5k4WLvtLW3tqpBts6OaHBWPVesW1bB35JJtpu06cNU286z1P5ieitmhAkRcnCvzh49HjQBB3Sr5xcZITk45IUiOzip3F83fLf6CCFYVoogrJpaK6zenEbYXMUd5W0reE6pv7uCPhi4QmFUM+ioIonndGPjfrLMtq2b/o1cj1GgtvmzCSTMUbI3EeT+svjX2IUNYj6IjNKUZHY0s/DMotrbHFJoDAw2sdYaa9sqrw5pcQQXsxH0yKOvzFx+FYny+9Ip0T1BCULPHELCEQewVJotcZNeFnhrQ+hg0xxGQbLAlBknCG3cYRmBwFw1uctwu6HJ6rGyhOtvJXvuhmABynejQqLRQXSWzSnBq90TphnRtm2lCd4EHahbrWiI/2AXCox167tNmV/cH6/1auVbU5bxry+hu1VNL692wWM8n9Hoxqh2dyu76dYAD00BK4y80pjAAKhZDcV5KRWuIfiiXuIA9LpJpShAsUEpE3mYpECfbFGj3z89fsf+Y9SFeyGn0R7SxvCE4tNLv8FaSpm75xDhmeZWdR3Rw2UlcEi7EHA==
  template:
    metadata:
      name: n8n-secrets
      namespace: n8n
    type: Opaque
