apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: n8n

resources:
  - namespace.yaml
  - postgresql-secret-sealed.yaml
  - pvc.yaml
  - postgresql-pvc.yaml
  - postgresql-statefulset.yaml
  - postgresql-service.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
