apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
  annotations:
    pangolin.io/expose: "true"
    pangolin.io/auth: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Uptime Kuma"
    gethomepage.dev/description: "Uptime Monitoring"
    gethomepage.dev/group: "Monitoring"
    gethomepage.dev/icon: "uptime-kuma.png"
    gethomepage.dev/weight: "30"
    gethomepage.dev/widget.type: "uptimekuma"
    gethomepage.dev/widget.url: "https://uptime.elmstreet79.de"
    gethomepage.dev/widget.slug: "homelab"
spec:
  ingressClassName: traefik
  rules:
    - host: uptime.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma
                port:
                  number: 3001
