apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
  annotations:
    pangolin.io/expose: "true"
    pangolin.io/subdomain: "uptime"
    pangolin.io/auth: "true"
    pangolin.io/port: "3001"
  labels:
    app.kubernetes.io/name: uptime-kuma
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: uptime-kuma
