# S3 as secondary/optional backup target
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: s3-backup
  namespace: longhorn-system
spec:
  backupTargetURL: s3://homelab-longhorn-elmstreet79@eu-central-1/
  credentialSecret: longhorn-s3-secret
  pollInterval: "300s"
