apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - minio-secret-sealed.yaml
  - disable-local-path-default.yaml
  - recurring-backup-jobs.yaml
  - ingress.yaml
  - servicemonitor.yaml
  - node-config.yaml
  - service-patch.yaml
