---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-s3-secret
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCMrqdfhoHudun6R9k1CvMaMiQofJ44BCcjCzAZbRxwHwrFpjFOiCUbBW0f5bRiMd4JYjPBA2JrwOE71qwJqdXRSNa/+sfUPiP1SM0PA1Dka6PtcvySXJsLIxkHOgtQ7bpXM126BHB6nRP1vCmRD3Etqy2O+04P5BkD8+AhcGlLYZHLsPfL1q+JADAtG5pF4DfTWUrouR1EfYhgTkYfxwH6gg7BY3CJpzZSHng1u0RDB3ZsbhD7gMV3y14yTd6cj7x5NGYcqB40Q0fZAVi7kOjyeNOH5Bw/q+ax/UAWjzZcQPz6lc74L8vuuydqqQaL2gcxxFyG6HOGlX51VQdgTKhqEdvbVkCWToHF3zbT/EKEZuZ4/dMR+GBO0O45BxHnxgtU8s3A0BqXz2PzzdweKei0FhPmEyInGD/TbbYSuBC73j56nB+s2c5xtfpjJ/Ftka0+Dw1/9N4djPJF3Kk4S2oB6KyhiZrj+n9gcJ38WDLSeA9q5vau03VePT01VA63mluA/0Vs5ObtRdC5lWUlyrRRry3+S9Gzz2iIwNOlEdMkg3BHbxnTKyr23VambaLuteIPUWk8+VwQ2VxdL9wOUAf4oOK06sNBMRaU2+8TXxvDADN15P3fc5fdSPbYDR/ldLnEe+cIoYhexYxzgkxC60Q18rysVp14v9ZgZwoBwb1Y3TQ0m5kPF7eZEHnz5U8dloRRia1Jbv/FOEElNCG+ND8uofo9Jw==
    AWS_SECRET_ACCESS_KEY: AgAKgnPm/WR7Fu2igu5F2uZ1foShdTfhlHd5j+YPYI/fkdd+U5Qf2US2mb2AsCWEZKPmZRZl8OrM84FJp+JqRoqJbk+lOwWWQOVCbCnhOmABWqqzFNIMZyBWJtfbqp65r2m84fv7brYOF04u/xZ+sTueLk2qphawgssi/58L5FhZ++uipY5BpEI9n3shEhrZURPbJM15jAlDpjZ0vqSWlMYiYVG14bApTLqovP4SeExhfCkiT4j4SBhDY+MkkW6hY+K1YQT+e81t55n0oHGx34xZcIiEhuv11CQJonTRkwYIQEUFEPv7JoczlL2pH9joKQsSGZpfeIVYObpebmoohg+RrMEc3Ba2TzsIBMwokNdwmTLwKZfGJuOIzbqKIKH7v5oKh9RkuSn6sy432lsQXxIQ/ADpHmOQFiJ7s9uJyT6DHTJoNkZu+xgJcMPpyqglBjssCxssvLEzszD3QUl3tn8ai9rGNOb7p0j6dmg80WKxJPGCQt2p5ywWMiXmd5RaUUnWM+f4FW2fURB5eWCKenLE7JOg5gIxB5aI/mz02JsLoQ7VSGaKjD0gyRIvirmo8+xLOIoSPsTfxqlECRdEvK7QEsD8Pz7gPs2Tr1FxfC7dGC4cYYbNujMZJUhx/EI5poYx9pKja1ozxszn4GJl4SuO6GWO4xsB68wXZ1q9G4Z/V1hUzc/XZ9ldYzpxzIw+NjA+JHRnQ4i17pg9Kbz1CNLPyYfz1GwkKuOU/sg/jJw8ZQjFWRx+4MbX
  template:
    metadata:
      name: longhorn-s3-secret
      namespace: longhorn-system
    type: Opaque
