---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-s3-secret
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAwqfSQo/FS86EpV7FR6zBj6kTfB0mhFRmAvqGhp1UiLy8/v57wyrozBRjA9kXL5TEeDKjvjMXzuZPiZz8H0/vPBSV03CuRFrofjeLjNNzsmI0aPn/XDJhIcfIuXwM8iLHyJ9uNE3UH4MV+ecwA9t8zgmcD78yqyerzgpa82iQIWUvTE9o8s67tQF4cXbO6og5CeI3gjUwRCYO+I7a6srw3WR3K4eAV3ypqPem3dRV8XBgvuQ/ctQPh+lVVQYx9nFsJ9d0K8X9PLb/Fr6w9M5gfpZ84wiHU7ld+eDZtENO9RthCKvJwCrKbP0Q/3AnIH9+sS20C57ErT1aOid2yYFP+RfRP3PnBwKRzfnsemvZzw08Nan1Evnng9iHBPzyhKLIpZ9tfo0CVLzK9w6N+0fNguCIayiSOw51Ntv98OVbcPlrFdlN67BwNImSgQ81oDZRV0FnTSMrEaa9TBW4qHZAXt8lDF4OnKOGBHB9CNO5pSb6lgIRm6QY+p8eNw77fvml5vyZECWj3wJqbJ76yUQKsdXgxVHpJ8zODl22k1UDEiU/yxPo6+cEo2sIkj0NoA/6SVRzXQ8ZUhiVXA2SXDQBlFBvtniYsUXR/ErYtHjzeD0cZKywiWP0cYwa7fqKRmlfxm3iWzw77jhvEvgzXdHNmaf4VOst6s0Wx49lV4MQUp/HQnsXZ+jz26Zg57vHp/vAC90huultC5PzyxxP1tY9qAj6EFw==
    AWS_SECRET_ACCESS_KEY: AgBcGGn4yqiZNCsqs0nVd9JLyleQwvFJOHQ5mT+kk0ejagZai6F8j9dVHS7J21tyZzP9MyIOWma3ih6cdD9UQAYCT4wth0UhMSwNXgMtrMmHUnGui9x+msgnTpBGFNpZcWoe7pxAmmgWeirdDF8vvNUEHT3HFR/zRYdcBVPT/J7VCLUotdeTDk1socpTlznTxFNGAFCYBq4Sw6rcA0cw0wpMPfKgg8b88Gt0pvWprmhRm4VlTOX1xCPrTQPQ+ld8/9dsJIaJBD/O7Kk9gt3g4Yn/0gfWW3x1KGZF1MwCE2vui2B8c/NB3yyzw/txHOWMYiFlPY/Sx5FgquzLjpLIa+rjnklBfVm/x/WqtdtS4xuedDoCpx6KnyzZvE4E4czbWT+kMbHTng+lQINEydjzGWRttjqObs+6axZIlmQyH4IVBYO7mtIhkSixghTd5PPcbk4McNwNsQaAgEkdWQvfUpyHTAPXhUi+FQL4jIbhHEXXDH2P9t13xSWhlKmapwFWhATcqhHPkP1aJfq6T1Cimqe8PCPGi9TtJHRBzPr5sUtMo9KeM9gDiDLqVx0MYcC//MaNGV+KyMHNZ4sLwttdGuXYJe9d10n+6zRX0vC60D3REogpWf0DWSKicID2AtQAZd8hWWriJoPPj7VLakuQUfh/3gKovKrwKGAb8CQgxT/WsS+qM0s3FDngHzEkA9pYCe9mllyfps+syp46FHLu6vWDUTgGAdqFIfTKvXS76XP2bu5uS8eAEIRE
  template:
    metadata:
      name: longhorn-s3-secret
      namespace: longhorn-system
    type: Opaque
