---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portainer
  namespace: portainer
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Portainer"
    gethomepage.dev/description: "Container Management"
    gethomepage.dev/group: "Management"
    gethomepage.dev/icon: "https://cdn.simpleicons.org/portainer/13BEF9"
    gethomepage.dev/weight: "20"
    gethomepage.dev/widget.type: "portainer"
    gethomepage.dev/widget.url: "https://portainer.elmstreet79.de"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_PORTAINER_TOKEN}}"
    gethomepage.dev/widget.env: "1"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - portainer.elmstreet79.de
      secretName: portainer-tls
  rules:
    - host: portainer.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portainer
                port:
                  number: 9443
