---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  namespace: portainer
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Portainer"
    gethomepage.dev/description: "Container Management"
    gethomepage.dev/group: "Management"
    gethomepage.dev/icon: "portainer.png"
    gethomepage.dev/weight: "20"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.elmstreet79.de`)
      kind: Rule
      services:
        - name: portainer
          port: 9443
          scheme: https
          serversTransport: traefik-insecure-transport
  tls:
    secretName: portainer-tls
---
# Dummy Ingress for DNS sync and cert-manager
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portainer-dns
  namespace: portainer
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - portainer.elmstreet79.de
      secretName: portainer-tls
  rules:
    - host: portainer.elmstreet79.de
      http:
        paths:
          - path: /__dns_sync_only__
            pathType: Exact
            backend:
              service:
                name: portainer
                port:
                  number: 9443
