---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portainer
  namespace: portainer
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Portainer"
    gethomepage.dev/description: "Container Management"
    gethomepage.dev/group: "Management"
    gethomepage.dev/icon: "portainer.png"
    gethomepage.dev/weight: "20"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - portainer.elmstreet79.de
      secretName: portainer-tls
  rules:
    - host: portainer.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portainer
                port:
                  number: 9000
