apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Grafana"
    gethomepage.dev/description: "Metrics Dashboard"
    gethomepage.dev/group: "Monitoring"
    gethomepage.dev/icon: "grafana.png"
    gethomepage.dev/weight: "20"
    gethomepage.dev/widget.type: "grafana"
    gethomepage.dev/widget.url: "https://grafana.elmstreet79.de"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_GRAFANA_KEY}}"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - grafana.elmstreet79.de
      secretName: grafana-tls
  rules:
    - host: grafana.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: victoria-metrics-k8s-stack-grafana
                port:
                  number: 80
