---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adguardhome-sync-credentials
  namespace: private-services
spec:
  encryptedData:
    password: AgBoc+3Vnj5JdjXq/OIlfEqg8JVU/k+kG0KSkC735PWMmDo6UoWQ0ZnK9RUDEk9RmNW3g1UsOM/3RXq/HT8Wr1Z3838Ms9Vmip479VyqQF6SRkj9YvV2+nixg6/yWWdRnGQ0TfRDGpGtipZbyffzSFUwqMm0kBCC4BtPOOd5IN8UyATaMLS/w848FbUfSdxxm6jxUVXQlThqXMHIYWvJcHMaGWWtfBdBaFkFANXP8nPvqoPb4PdD+S5KvSFARZlAvulykUZr5rhQRl/m1fHqN1MHDVBlNhNr5PNgEsGysHWuNOffRwaESGaC+vAS+6CENZkU0WpsMXXD5Kaq95lRBEE1Bw2u/XtBg9a5rkeCYEg5dFuNFTQPAVaJBBUiLwAzANST5IPC+KPq8iwt+PCtdatlSwS1AIJOpB0cncq7XYpqpMXlbK36io4sIuq0G58ILooLlRwEgF4QFhQL0Cb2TxAFhe85UkOWWuNoa3/qGevqIP2T9Q+SUxhNd/2NR+ulyV84YpWZwLA9MyWeOv7M8TKPaDVHoQIkfWYD4Gt+zW5v8I/NSOGtH41FBK7hsLcv15F3RcS/ZklhS5D7npM5OHVjDChvbiqR4i3ZG01xiOL4FMfTIFS90b9DtyagEaiGt79pJitiY0SQW1/QYQ0U0/wHoaB1h4QCKt/9lcJ5nvsTuBrEjhUhEf7dBJ2YbuXxSy4JY0rRiKBuE564igeT8LzdeoxD6w==
    username: AgCaqODyY1+uM+4wXuk8o0YIyB+aDgMhGxmXvkt5Pd11c35I4w5DyVw/HdVg+fmFerPaPweormC6yjAqpnNnHRMN39z6qu4+Gj0JXsyjxxnsbUO190OEFwZ39gQOxovVf96yyNrin+N/AgFEz6jLLI6fG+lJsnmCOrJegypvGCi2sOaSrxT2HqLiQfL+TwMtDveGgah3LtUOQFzt74Cp3B7IFnB7eTCdcX1TfuFxzwk4hpoxyG2N3Tqgk2x0sA9ka3RRCi6O8yfgw3SUeo9m73zA36ea4dNR4NuyzWVaCrrQ9TiCP/3iioY93UcdX8dWtwR+Zep/08U6fghMOSP81kUsLtFoTDH6OzwC2eXbw0bFat7KyNIlM0wF0fkbVVHz8Jmp6VKXwVQunmE6IolKPkmpE8BUDvN8v3gC7Ofi1K4Z3OdyyXm3whlJEY4Tm1jHyv5C8gNajB5hmsgibPizJJy89cgpDAl9HMCwsP0SBsAiLhbRW8obl/0i5Y5NDLcHkbbbY/nQhW6Uh+PXUsyZiCUoFdf2gBuqTDNZDUVjjTiGtPHQat7qzG3L2+mGj2Nra2bb+/xMYjg35YGMYSQ4q9KKjuqT4w8PIqb5Oc5dUrybNJMIpzS2OKPC5WgZUaVlG2/QZMtsPg5NPg2gJrhD33DhW+g5z3gbOa2Fg5HLu/BBTIOZkM+/AnshLYKwx7AgyfSpePH5
  template:
    metadata:
      name: adguardhome-sync-credentials
      namespace: private-services
    type: Opaque
