---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adguard-credentials
  namespace: private-services
spec:
  encryptedData:
    password: AgBaXOkJFsbERsTVBOplPNu3sP2VSUUn2rA7kxT2oyej0cPURgrEUrq2GSfc6xePVZ0O/84K6ofqy5rmHfUVes+ixsY1W3hoIb57GTMedvcCcAqUSskgSuPxeA8m06eWwsIlwXIIkGdf+a+OieasaKOO/aN2w8oU5j2vAG0u+KMNvAGQABd1FnO89mJHmstLrcJvVagQcP/hEWGyKp1GDmUoPW+muK9rfQslv7LYjT/wKPeTcs5CdBLvY1FFAVfKb0WkObQPI/wY7JiD5/m5fW7LhnJDV+4ZxZhcHQEb/lx3cpwB+ZPQz2ERLWHUgDsqbAp9t4dFvBYLTDk/5YshDIM7c0QmQ5znkl5LFrKJLBIvQ6DLMQ5g1HRGQd7SFg3wZ5Bs5C/ZmCwmRDodgcoLhfG1nicBq+D0rR2hJWS1rmI8Z6lYa1AWWuzrrEV9S3JF3/l0P8OOrFj5vtV0fePAxC0o+pJtoqwCkLEOBHs/IhvLBSKiqIyIHcrg0YesepG94cINOGz7m513ONPc8eaO626RPAi9BVDOPSmI79zK6Jei9skxSqp15pBp752ZB9j0skcB+kG1xDP668lwicvxjhJx1xIgCuc+x7/wj05wBnI5ds5R1xQelQNFVk3wszAMXkXlE/SMfru+g86ml5wAxRR1k0LVTwO8W8pKyh1vXI1Jav8vf4bqFSirqR23aXVYOIeozTnXG/DJdcORyi8XslcQOxWIfg==
    username: AgB709jzYDFDLq8nJ1OM4kfs+FFNVvELrN1dOw6mqDQfAbsYZt9pFImtlNNQK+JMQiJARRi59zMe+3JEPkLh+edMOAmm3H8cd0d7sU6Fn+o4BBceibB+b6fKPTAUOHIe27IGFvLjdce6SQpztfuIksmTqYLKjIUa0bz7ncpOLFH6sz0VgZdqUZxwt+859pLi+VTQZGU4s5M7qKsNSsozI9HErtMKcxWDIEMR9t7/Ru0lkHYNr7oeAm2PJ5KaN2+cF4QgFbx5W+LK5vCR+3ZSgo/jIqwdk/jVUocBzX+XswFEL/VtGcA+tSWF1i9xXHlSJo1qgbmVKYjmtfAKidE5Yv9/C1dWx61qTvScHl1waVnmWkh7D20lUNvuEHwY+1pXTEKLQ2vN8XTfkqjlxFwSYoRBpB1EBma1wUo33if0ZHMX9AlATrs8iSWj0+L4N5Zh+3SL4CzJMkkpMc5JVHqsf6u2+TW6oAKEZTDXdX86UQQwmzh4MrEVROOp+3hRd26QVmFJl3e4hvMciZj66Fu/8dm4tPsIaY7/yorwTdirOMTuIMS0rrSNEbnEGJ23i06S5pMjFtfJbLoAyQbNN1J6gknGotOzCFf9hZ20xjHqiM2BN5xSbgb9vf5n1DSQLKxaJX7m9Cr0nLi+G4rB81z8m0ebZppuh+8V1O052vZpplvYoI3YeQRjAILXYGQ58KlUZCAmny45
  template:
    metadata:
      name: adguard-credentials
      namespace: private-services
    type: Opaque
