---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-macmini
  namespace: private-services
  annotations:
    cert-manager.io/cluster-issuer: internal-ca-issuer
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - adguard-macmini.elmstreet79.de
      secretName: adguard-macmini-tls
  rules:
    - host: adguard-macmini.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adguard-macmini
                port:
                  number: 80
