---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adguardhome-sync-credentials
  namespace: private-services
spec:
  encryptedData:
    password: AgBMurpMp7oGQZZ7avlYqlNYs/aubxlbl6kG5SPWt/YN/9GqXMPu/iztZ1RJ7vCG9dDrsvZTupoLoSZJRW5X2mK53Xrr4fCnZ1tVK/OcXgmZ9Jo+1RRM8KSOHD1rq49RRTBaoTP1lxIMICwkVSuMHI3H9qyq4K+kzyN7HCJU1eed6jID/iy5A/X3lLP+Sjc26dGQAUdpm5Dxo7JPFdaRRxBKu0M6hgSnaZD96AKx5SYPsa00pwDEgzBcIJZkXZAzN1DRXB37bFsVwboMKDtzS+IX1CMaOKUgIxgdX7y/APmLTJGEPcsR1O46KFARBlmsj9WnsC8ZAEr2aHZ7xs4PNEfcjO5l2R9KZHAyZn+tdCP5S529LB9/saJgX+QI0yGiCPDpGMmQD3KyqI+W9eDZGg7uEQPO9llZO73udB3f9ggfATEmeBl3vgfjygj8O+vlo0yevbdZdtTpfvx6nVNuHF+NzodL0Raf2WmBnFuiohxteqO9lYaFflHeakDe4P3eS3PuTKrmWSQAxeGlyeTgD6YknV64EPnIPmgpiZuSPnz6mtkGD6pX0gp89wD2VKwpMQ2S+1eV3i1bFdAeIiul/DCkb1igjIvle86FqoS0/SJ/Uwbzf4ioAItIcHNnrb0EtbONN5nC6n6f1HXD/7bmR/zWrVdnerKkJOXsS6PmMacONG8VEkXPr13EqquRJAdUtwh2aTnJqWnVdo/jry5cBv0aKNs7kQ==
    username: AgBPoG8hUpWW1L1VJprPtkg2jNFpXrk/7jIoWMumtV7VHDYRz6l34mjvinaXtjokEGSXzFPkwMOF6dsEgKjrRlmEC5gQAGojoBzwJPY2pyHI78v/ZefvVrKkZ/GlmbcH9oPlrwTPE5DA5O2UTzjQ2Lf62VGE781MqisEkT+RVZrVr+rgNwMdCima+bIroVBOJJo/fwMrbYLrg6P4yt6HnlOCW58Y4Xn+FCRkr954sfXKQtgwuDna0CjrVUVbMZXxJ75uWFI2Dvz9Mx7CTkf8dAHzuMvaSN1n+urKFvtrwVHvejlRzNxJzP9wGHGSVp0UanCyZMXp8PGVTFtEyNKNUEOZDlXGhhbZY1ETB77cs1a/3bLpnZUxjPLzfbZH1JVA57XZnGuiH/Aw3nf+WKTRbSn6ugbX0h2wqsvdODhwRMg0UlEO27yr80SmZXMsxgzK1GbW8sh09i0aqFKK0f2RBb+70eIoW9AuSeEMIEeU0oxz9/k0bDr8fug01IZQr6Ti1WdwezzqQiHlF6tn+EbCk5X0nw9RW3iqq8lsPsnnx759fPmZWJ097GSTssIT1abodDzvirLmEybAxWiky3wigT/6ucRTmMMSPQnIugKMu6MRoPCztjxQdAK/KagLqvyICgdHQvkDF+YNsOkm5og3rUgSy+knmJp9Nz/KNpUI2zVlKV5EUIKai+FBjaighuyUvcm5FxrW
  template:
    metadata:
      name: adguardhome-sync-credentials
      namespace: private-services
    type: Opaque
