---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adguard-credentials
  namespace: private-services
spec:
  encryptedData:
    password: AgAvrXIJIkTMHtznxTfynjZwUkHAeWUHmYZee6EIL4qE2OK6O2TIdgWVVgRypwdqcu5NjLqPkD8PSjP3t/u/eMFKU6JGjNpLf0V/ECzXd1olo07LFhaziWGbssEvO7bw/mDzrPa218F66w8MjDqIIpg0wCSMDyie2bDhn1B396JW2K7UfXiDOiBZlQpD48SBVsDcRZ6vI0eV6NlFiXYq1nCGDid7b4FTbAVmOphKYdLfG6NxMqX8DgOLFvXcC/hg+wgsgJUhspCgKUp3Q3patJLSJ4cR5lQJxPWZdmJzx0riPYPdNmkQTmRMfeDjgvhVdcIyo4lckYDPDsVrGIU06BK7ULkRSvLMlad0QMgYAweUtkUsDI09uZu9hgURZTqQDyeOMgy3oTngGx6cxhqJG42l96YuMK0Y7dhhp+4ONqu1DjijINqYX6+d52pJ+B6DTaZ4zL9BzEb9oeazNeJodknwqTgiXX8WAduS7iKW3EAIMyJorcR240Jan8fKrxrlvclkVcaX5sGDGwLSr2e8dvcA2UfNyprdVc86RSgUl+DCCOrYJWL1c5lmfKPUm7Kcdd6g89uJaJcBW0rjHqaSggcCyqNSqueik7zwQYOXCgdWi+y1rCjt4f1zRsmk2Nht+d9kuG+N0o+mO/2AxFLJBzleI20+SxCHEbT5Pw7v6KRYV321l0+WqpysfGrPrOWPI3AA6QWzaCd4+x8LCZjp0w2aY+XK+A==
    username: AgAweRrquksV2nGNYuYqYolxwkXWbPZuhZ/cvB1Jm1aAUwSMVI3x1ohJ4sVpXfq83Zro3DAQmj9488dulMVUbh9IlVM6V5Mx8C0AXRVK6EJTI1RRgoNKOF/qh2jGFcx17AdXMvz51GH2I6e/qaTECe69nR8cCDGt5ERYNT379qA//H4M3iSLTjrtnwRWChGmwwpAyOZPASNPhOITSA+ODWRzidFOSriTZugyU1+z/lcvOdZRsnAa88zBDaMiqNc0a6k6diLmrHkCqdLWiRaVzrPRlhl9g7dNa4FQF694+448Ir5kikxEB+vEFAbr652DFSmqr+jevcMeRJicqsU/TD65B5wYpBOnVSk+CcTvjgBIqNGy103jHn4ccVX951ieNq3+puorYk6gEQaoV1G4U5llMRANwhPGV+Jinroog//vd3R+T7sfm3BQsGiKoMVGHwgmFVcW7lsy3efzoyKpQB12EdkfPTjl0jn8QBDLeoXZ8Ikeq+oj/H+xoQapYIPdUx2ZiMdlfyzUFwrLGaO7RO64j9nJ8Rg4GjcFL60enXZ2xTg1MEkNJzzeyd2OSHVD9Txs4Kvo0T5TqSrp50fCprj3ll3Lm4tlW3DS+aeftjgQ9T+zV51lafSw2DwvNGgLKBDHXiuXmf0+rFP2SXClaEejVPxMsdtImILCrL3HZGSbAUzfE8FHgbqi93y16agSatogRPyG
  template:
    metadata:
      name: adguard-credentials
      namespace: private-services
    type: Opaque
