---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adguardhome-sync-credentials
  namespace: private-services
spec:
  encryptedData:
    password: AgAc03TpKnCMKpF3iCy7wMlBpobt49qKB5QpcHFi5+FBrizG1ljOAltcOBEEAIt5LiMTYr7T933+zmITnAB+2usVgxS1myud2WFezkznZoYUOrB/aTUZlGIr2UV3DyG2Fmi2qT0b3Z+XYDQUsdrQfpPH8ZTQF699ONdRyKZF5SFmNUHECKIJOQt7OYqmh3l4df/HvmBnOVCHo0YK8eRubjIhuTbEphSotuHRbqsovQ9rCpu5t7wTX7wj2WYhyUdm7VH/fzBbg1vkcd69qhtUgeQV1xEdRYSbeya1vFmQvZpmM0KrPSvfBYWwCb4CCI8Hlwac8PA4NoxXnG066hzfQOmtMmFNozrD+lBg04lEag7Oqa0dXpaV7Pc16Ld5yCST8j0GebjvanF7x/s7OFsxVkrSCL6p+NPLHbejRRYAIwYqoVjoRjpJaWu0XueJs3+5qZpiNkIai3Lqm7MtKyGFIDk7KG0gmV0C/RJxHUdCtpqUrwo8KAljoRrR2jk9Ez8Pm2fb8vpcxvKfLomBltCemiFrOZBRFoUZPuKIN9Rp34+5W/VWwMeUAGJ/CtHaonWFOEyYZj8zqEgm35T/OiPKPqDU73N1zR+m1faTj2yjNN1LjY2NMsmG0z6CX4+p0cTASxp/TXL4zAn+Ili73+/Snv2ksZeP5fxxl0ujiDU18x0Vi9XelSm4rJ6Xv4cXwJugD50SIjCZsyo3QwBCTabd+ZRJfXdqPw==
    username: AgAGF2KVEtZLvA4wZAHZUeupRDF8R+CbD5YOtG1kEDUnA/jcLKq3DEZOMO9zVeNjr+6McCRNWp8Ba+rpd8gaVpdZj4tf8WMgBHW8KT9LXszuqgMcd21hzvpLrJMiv3YdyafQwdzIg0VqJGNf9kZs1k4qw1xMVUyGev9NglvrgHW9rFB+k5YID1t3nprY5lUdmiVtzEZKVZIwjRQswe89xAFk6KBv8xguZY4AdZB86tDEN3ihYOPqSP2Ma24K7R5VsjFeYdBJ5Y5E9jd7gzM6TyOO98Hw/YaN4V98W/9fbnlEwsJFXsh2/9kd1kho6OdO+T8Q8vDkA4IVewkG+VSoJ3PXFQqggAZOh4b8UCD8Nq1qxJUvtOdYjXvPcWX6eennuPpJucW9bM2aXC0zw8fWQXzmRKVyMn12WCZkaYLXcTXjVzektHPde0Tdy7SIKa7My+eE1CaVCMHdLOC4gNX0iwy+jOuwpII1Httx63xHCEJfTGWoE/KEIw33qsSFLei1vZi+UWv7/Yy9Kk3x7p53LHdAanKA5+/by1yds4UxgobL+FRsZRg/GoeDtnwWZ6LPJHk2gUOv795Ou/cRQ34gMVz5pf65GKAWxNfxIOa10Eu1vJKO7aGuNRmCW2tFD9YYAP0XLKJAkJjJHQa7o+pOTMiaGxeku/EEV4xppGtlx8Arj92iBI6zQuv1PiDO8vgAAmX+zoDX
  template:
    metadata:
      name: adguardhome-sync-credentials
      namespace: private-services
    type: Opaque
