---
apiVersion: v1
kind: Service
metadata:
  name: adguardhome-sync
  namespace: private-services
  annotations:
    pangolin.io/expose: "true"
    pangolin.io/subdomain: "adguardhome-sync-web"
    pangolin.io/auth: "true"

  labels:
    app: adguardhome-sync
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: adguardhome-sync
