---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-pve
  namespace: private-services
  annotations:
    cert-manager.io/cluster-issuer: internal-ca-issuer
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - adguard.elmstreet79.de
      secretName: adguard-pve-tls
  rules:
    - host: adguard.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adguard-pve
                port:
                  number: 80
