---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adguardhome-sync-credentials
  namespace: private-services
spec:
  encryptedData:
    password: AgBRNMfwlQas6xFgtVp4uFASlhw2nNmo3CczXH4Wt6OJzuCTmS8v6p+fBan41CUkl+8DGeE+LFYvs8FNX03+rDpkSDziMGwd1SF5+y4lzhtYdHmJ3tkKeHDairA07DOIcK9ugHZBV0O95wN5rCY4mD3aQCYDSUk1ocFdYowPPcUp3qFPxhFU8lpeTbB80JP6DwhzFeba4MSzbjrpQkKMUWLAiBRzQGwNRhtfkNM3STs0KsisILR51ZKEkQ65Q0qBIFZH+/tclF85+KPmCt3sKavP6Uvtq6qtf3SDmmqKWZlSbYiXOzFrEL9TVDcZQV7AynlKUjjl1l4ThNufldFki0U4sCM0ASziIeWbWBM7LpmUIYFv3dlM00bcjm6Ca5YPuxzXRTd/+lSp3lKdNqkdlbyHcFd+D3x/Zn0ivMPX6tXH3bPMNTwVyR6WF93MNaco/rfUNEh1iPz08Ucd9bZaVtHMmWINNKi+3FzYUhp0h9VYS1qQ23GRDDheroUNsi6KMM4E1zBdcQ3v5t+IIB/nCtmsHon/8B8xspetn74aGQhO0dqS40yaJkysuNjP9ldWj6GBFDcPbJUbOSd3n+PvwcA/fy5wwpc2VWj1UVWJWNcBLBpxaPh/nm6cE3I7AypLcdykN+3EVM9v7dN89YWQi2izBF1KEytgkN7TeKODF+VN5o8v4Nzq6rTCHVOYEeLANpwviBR0Mzok8Ysyqol1DIJgXIIvJQ==
    username: AgBWuO0ajgUiA4aZA7YGn5hxaFCdHqH/O1YX4AqkD96Bo+hLSnHT+88/x9boLTGsIty6IuVO4rGI3mk4jtAS3c8wd9ZDcrJf7EmOs59q7r0/d/jLR7CkGgSipBONpDv4BDHXK2QuQ0XVlhEOWuVH+jJU6dN99hR5SGk8Bfy+tpp19/jALHQddV87aFbXYtmKkg2H8rlLPbsUTwgWwehv0ngaqUojDJQVq8v9EpaE0n4GgKH+sBoRsBt+8/SDe65vvFTmJuvZ4IuAkMFQtdqV6bBAnybuWY9wblxxm4f5EfErlicnGq4w5sqK1vdnm8iGcvzzz9xlBKkEsPVa06bxaQ2qLWYVQjiC/8dUW0UIkP3kSBgdKUoromIUK8roEMzS8pd+ui/r8w+9rsmCWiU7jDMXGgQtMqvKfw4ie2owmz+/r8yizCQX0D5mC/KHp7sENQa2boFL89Zb2GUq79YjbJF3cjEkINUgd0snOtVKflhAM+JI0zKTN0xkO2yPhlWvJmbgp9hS3feOaxxbK63bqJYyyHfi0veygOpY2x9SlcZaXl8EUecPdXtsvpgHNqhqxfGy/rXMSQQrOHu8FcbRFj5elghEsizuy0U8VLFpiwpFFlbYqmrfGvpMHNhj/AYBbTFTT6eQeOu6TbhNVwfOVFJSwX6wNMjcsY6kexfy7Q8OIhA39C8d9nnjPIV6ewfwSsn+rzaT
  template:
    metadata:
      name: adguardhome-sync-credentials
      namespace: private-services
    type: Opaque
