---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguardhome-sync-web
  namespace: private-services
  annotations:
    cert-manager.io/cluster-issuer: internal-ca-issuer
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/name: AdGuard Sync (k8s)
    gethomepage.dev/icon: adguard-home-sync.png
    gethomepage.dev/description: AdGuard Configuration Sync
    gethomepage.dev/weight: "42"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - adguardhome-sync-web.elmstreet79.de
      secretName: adguardhome-sync-web-tls
  rules:
    - host: adguardhome-sync-web.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adguardhome-sync
                port:
                  number: 8080
