---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adguardhome-sync-credentials
  namespace: private-services
spec:
  encryptedData:
    password: AgAwG63DfejtFeTGK/V750lNNs3NQA5arcbnPxxyxaAtl6H7NIX972or7lv1M/QMZRJdF67BRK6NfsUVWEobywojTIIRGbzGkYKBteYHNQWvZqV/EPlEuk0U+MF5RbyrIDfGHMg8DZjy/+r6XTj7zfQ+cPLvVQpSY8p4DcVqI20TwEfxEKqkbkvoD5On0xgwrS6641N1w4wREhvxPPcZ7aIWhF48uTQrWZSZ1NEiW/7THlStiEoYIzHflieuOpmGMajFNvkqfR36hHfoaSgW3tPYDZ0/O49foBMlM/1S5L6secoZSkeGN3CL9UGhRJd00M1iMBqzhF6oYJyeTo4zGmLXB7D7Q/fTqjqOx6hEP7U4g2bwfWkCaYYwZqsT9LW7dEFhuKm1OtU/rcHlNW+++xnu3kayyYim10zuyws9TkyC8HxBKVw53fIwsc+wgCK5rWeHqjCYfGPaDpQsou4fWKHL8HljVxqBx3mcvgTBw0O26DZh+LyXVwrYbr521NfWBweVw5d3403CayhVXK+TK5gS7xA+UI63RqbL0pm021w5tVFnu19rmbqKF0y3kKX55l5RLAbMRpBibluuJlI0N41oemBnYdCP99k3EhvgUCDPRzUEflyoKiAUddOfJgeeEZCtGBC+W6tN7aoDccTrb0JUWx2y6qWa+WuTNrRrrrs+z8jSPVqdgpFPcr2MIzkcV6NfLg0idgBmVr1+U4LtReEed9UgCA==
    username: AgCmr74iu+SPYg5qXMEcYc0LLaMWI8OOt136dwiPRIEkywnjdDELwT/hYqLxB4hEimY34lCflYMUVKaqXOhSgPohJ9OFmWaM5ow0MC5x3OvtsAzkYOfyLgRCyCP1ZMI/MOEETWReU8GHEUkLYUGzK+yRhtZ3GXQHMxnOBFWQqH8T2wWfOKOhf9zLiyTu2k2YA7qS3JjJLAoXEg1G3iOGk667JLG7f0rIzC1Uy+15tXI8MH5eEhrUhysjBgySFoExtUyHIioCVswXYeUhJF0poajRkI4CniaQEs8VXCoX4F3CVJMbYAOvY/hQe8CyImV8P/tRMlfZSubMjW0SBpiVbsuL7h9fvZ6c/gRHWzYX+sOxRQt1CMM8meTgt6gQIGInIjyvEjYWFu99LN6fmCTTwZvhJ5l4SzPXyaJ2zzmWbG3yVuYVtxv4ZSelHOubrm1wsWNB/WCL13Di2yDO7XeeseZF7IxLaPfVJzgS59dTW2903QuEGBghQxQBW3oN/ccyxXPiCfsetb09a/yaUu0ye3CTCPomQ4TmiZfuxFw32w2INd55xPwLjoPsGTZlMWx11xCDuHFurMG8UgIQAXQEpjvvWGHWD+aJQ8RexogSMb3dCUjhzU7jA8Hd0tzGGI3zPg0yAPoOUHRqSdybZyZ8BZDZP4dSBxdfMKVBXPp1ZRsXnaCWWHfemPAMqhdeTTFyW+E5mmCI
  template:
    metadata:
      name: adguardhome-sync-credentials
      namespace: private-services
    type: Opaque
