---
apiVersion: v1
kind: Service
metadata:
  name: dreambox-external
  namespace: private-services
  annotations:
    pangolin.io/expose: "true"
    pangolin.io/subdomain: "dreambox"
    pangolin.io/auth: "false"
spec:
  clusterIP: None
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: dreambox-external
  namespace: private-services
  annotations:
    argocd.argoproj.io/sync-options: "Prune=false"
  labels:
    argocd.argoproj.io/instance: private-services
subsets:
  - addresses:
      - ip: 192.168.2.11
    ports:
      - port: 443
        protocol: TCP
