# ---
# # IngressRoute f√ºr Traefik (mit selbstsigniertem Cert vom Dreambox)
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: dreambox
#   namespace: private-services
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt-prod
#     cloudflare.io/proxied: "false"
# spec:
#   entryPoints:
#     - websecure
#   routes:
#     - match: Host(`dreambox.elmstreet79.de`)
#       kind: Rule
#       services:
#         - name: dreambox-external
#           port: 443
#           scheme: https
#           serversTransport: insecure-transport
#   tls:
#     secretName: dreambox-tls
