---
apiVersion: v1
kind: Service
metadata:
  name: dreambox-external
  namespace: private-services
spec:
  clusterIP: None
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: dreambox-external
  namespace: private-services
  annotations:
    argocd.argoproj.io/sync-options: "Prune=false"
  labels:
    argocd.argoproj.io/instance: private-services
subsets:
  - addresses:
      - ip: 192.168.2.11
    ports:
      - port: 443
        protocol: TCP
---
# IngressRoute für Traefik (mit selbstsigniertem Cert vom Dreambox)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dreambox
  namespace: private-services
  annotations:
    cloudflare.io/proxied: "false"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dreambox.elmstreet79.de`)
      kind: Rule
      services:
        - name: dreambox-external
          port: 443
          scheme: https
          serversTransport: insecure-transport
  tls:
    secretName: dreambox-tls

---
# Standard Ingress für Cert-Manager
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dreambox
  namespace: private-services
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: dreambox.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dreambox-external
                port:
                  number: 443
  tls:
    - hosts:
        - dreambox.elmstreet79.de
      secretName: dreambox-tls
