---
apiVersion: v1
kind: Service
metadata:
  name: glances-macmini
  namespace: private-services
  annotations:
    pangolin.io/expose: "true"
    pangolin.io/subdomain: "glances-macmini"
    pangolin.io/auth: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 61208
      targetPort: 61208
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glances-macmini
  namespace: private-services
subsets:
  - addresses:
      - ip: 192.168.2.4
    ports:
      - name: http
        port: 61208
        protocol: TCP
