apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: private-services
resources:
  - internal-cluster-issuer.yaml
  - servers-transport.yaml
  - certificates.yaml
  - nextcloud-ingress.yaml
  - dreambox-ingress.yaml
  - adguard-pi5-ingress.yaml
  - adguard-macmini-ingress.yaml
  - adguard-pve-ingress.yaml
  - proxmox-ingress.yaml
  - glances-macmini-ingress.yaml
  - unifi-ingress.yaml
  - plex-ingress.yaml
  - adguard-credentials-sealed.yaml
  - adguard-dns-sync-rbac.yaml
  - adguard-dns-sync-job.yaml
  - adguardhome-sync-config.yaml
  - adguardhome-sync-credentials-sealed.yaml
  - adguardhome-sync-deployment.yaml
  - adguardhome-sync-web-ingress.yaml
