apiVersion: v1
kind: Service
metadata:
  name: minio-pi5-console
  namespace: private-services
spec:
  type: ClusterIP
  ports:
    - name: console
      port: 80
      targetPort: 9393
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: minio-pi5-console
  namespace: private-services
subsets:
  - addresses:
      - ip: 192.168.2.9
    ports:
      - name: console
        port: 9393
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-pi5-console
  namespace: private-services
  annotations:
    cert-manager.io/cluster-issuer: internal-ca-issuer
    gethomepage.dev/enabled: "false"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - minio.elmstreet79.de
      secretName: minio-pi5-console-tls
  rules:
    - host: minio.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-pi5-console
                port:
                  number: 80
