---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-aio
  namespace: private-services
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 11000
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nextcloud-aio
  namespace: private-services
subsets:
  - addresses:
      - ip: 192.168.2.12
    ports:
      - name: http
        port: 11000
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
  namespace: private-services
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cloudflare.io/proxied: "false"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - nextcloud.elmstreet79.de
      secretName: nextcloud-tls
  rules:
    - host: nextcloud.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud-aio
                port:
                  number: 80
