---
# IngressRoute für Traefik (mit selbstsigniertem Cert vom Mac Mini)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex
  namespace: private-services
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`plex.elmstreet79.de`)
      kind: Rule
      services:
        - name: plex-external
          port: 32400
          scheme: https
          serversTransport: insecure-transport
  tls: {}

---
# Standard Ingress für AdGuard DNS Sync + Cert-Manager
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  namespace: private-services
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: plex.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex-external
                port:
                  number: 32400
  tls:
    - hosts:
        - plex.elmstreet79.de
      secretName: plex-tls
