---
# IngressRoute f√ºr Traefik (mit selbstsigniertem Cert vom Proxmox)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox
  namespace: private-services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pve.elmstreet79.de`)
      kind: Rule
      services:
        - name: proxmox
          port: 443
          scheme: https
          serversTransport: insecure-transport
  tls:
    secretName: proxmox-tls