---
apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: private-services
  annotations:
    pangolin.io/expose: "true"
    pangolin.io/subdomain: "pve"
    pangolin.io/auth: "true"

spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 8006
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox
  namespace: private-services
subsets:
  - addresses:
      - ip: 192.168.2.8
    ports:
      - name: https
        port: 8006
        protocol: TCP
