---
# IngressRoute für Traefik (mit selbstsigniertem Cert vom UniFi)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: unifi
  namespace: private-services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`unifi.elmstreet79.de`)
      kind: Rule
      services:
        - name: unifi
          port: 443
          scheme: https
          serversTransport: insecure-transport
  tls:
    secretName: unifi-tls
---
# IngressRoute für Traefik (Unifi NAS)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: unifi-nas
  namespace: private-services
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nas.elmstreet79.de`)
      kind: Rule
      services:
        - name: unifi-nas
          port: 443
          scheme: https
          serversTransport: insecure-transport
  tls:
    secretName: unifi-nas-tls
