---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vscode
  namespace: private-services
  annotations:
    cert-manager.io/cluster-issuer: internal-ca-issuer
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - vscode.elmstreet79.de
      secretName: vscode-tls
  rules:
    - host: vscode.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vscode
                port:
                  name: http
