---
apiVersion: v1
kind: Service
metadata:
  name: vscode
  namespace: private-services
  annotations:
    pangolin.io/expose: "true"
    pangolin.io/subdomain: "vscode"
    pangolin.io/auth: "true"
    pangolin.io/port: "8080"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vscode
  namespace: private-services
subsets:
  - addresses:
      - ip: 192.168.2.4
    ports:
      - name: http
        port: 8080
        protocol: TCP
