apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    pangolin.io/expose: "true"
    pangolin.io/auth: "false"
    traefik.ingress.kubernetes.io/router.middlewares: home-assistant-real-ip@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Home Assistant"
    gethomepage.dev/description: "Smart Home Hub"
    gethomepage.dev/group: "Smart Home"
    gethomepage.dev/icon: "home-assistant.png"
    gethomepage.dev/weight: "10"
spec:
  ingressClassName: traefik
  rules:
    - host: homeassistant.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  name: http
