---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: real-ip
  namespace: home-assistant
spec:
  ipWhiteList:
    sourceRange:
      # IPv4 Ranges
      - 192.168.0.0/16
      - 10.42.0.0/16
      # IPv6 Ranges
      - fd00:cafe:beef::/48          # ULA Kubernetes
      - 2a00:1e:7c41:fb00::/64       # ISP Prefix Delegation
      - fe80::/10                    # Link-local
