---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: psitransfer
  namespace: psitransfer
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "PsiTransfer"
    gethomepage.dev/description: "Simple File Sharing"
    gethomepage.dev/group: "Services"
    gethomepage.dev/icon: "https://cdn.simpleicons.org/files/4A90E2"
    gethomepage.dev/weight: "30"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - psitransfer.elmstreet79.de
      secretName: psitransfer-tls
  rules:
    - host: psitransfer.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: psitransfer
                port:
                  number: 3000
