apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-webserver
  namespace: test-webserver
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: test-lb.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-webserver
                port:
                  number: 80
  tls:
    - hosts:
        - test-lb.elmstreet79.de
      secretName: test-webserver-tls
