apiVersion: v1
kind: Service
metadata:
  name: test-webserver
  namespace: test-webserver
  labels:
    app: test-webserver
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.2.251
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: test-webserver
