---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adguardhome-sync-credentials
  namespace: external-services
spec:
  encryptedData:
    password: AgBHdyGHcy0XBxvgBCDYwsEanZo3CrYCiVbX8ENxI9EBtPT65xbp1kaw95vk2OZjt1f5tfnDzWh45d3rCZBX87znNDf5xe0OhY3FhYyhVbA0xuLRSEwpHgVUsPrqpwn8WT6FQkDuluWLxazuQ8/utJjwiubU/UxhHCq2GYvodn7n97xqB1X41XzQXhhwa6mzqTkhvoOsOZZasa9Cmw0aGOoaoaVCuquQOzmZqOrlEpzh4rpPYe9XjrW3Y3gqsnxkxD6I8KlpIzUL33+ix6RqgzpH4EqBzTZC1YhuriZqXomYCDLnxFeAGlt5/UwoFqPm3okFa7Gf4jF0jB6YweC6580/enubW8ku/qsPf2rQHlRYJCTGf/tH9mcNne1b8CCZLUH6CZQ21DnN3uGph8wTXwh/BSenawPuVGxQB/H2X1RlM+n3eBL98ugL+YhAprR2n+PAkAAbgvrJSYGESZ7vr7iEjfXFsL7VZKSrGQK7iVHxziIPG0VlcUguH49CX2sIy7eilAmlaMKsP5bxPYYFXd/ROlGOIQLGteKFYvVBLNmnJKeANPhJ10CTvprDc01KHq0b4OJ68yp1hfAVWoKcw2ST8ijFhkU8w5yh5AE9sd2CrM792Wcz6KWQzlugZnmwlUFeu8MTWwlQXEi/olWlN8ZQstmzdIGCW02gKro11h5jMH/lBLufLMfi0nl8c8cga3GW1IgLZQZ9P2uQasfiXjqBhVdfPA==
    username: AgBnPSpcQLo4C1eCdUH0hEfsFq4ZuDVRDFViE2CcfxKSP1zhk7y6tSymNXF7a7fs3Z1jUoQAtS+OUT5K3TSCxX4ob+0DB8mZm8mKy2tP7yiwVR7PT7NgWysl0Lf+o7l7dUkSdgj69pcR6gpf+m1Wmyw92F3mCIzWAjiN4Ozqpdu+lduiSpXg0QbPNXHMLrqRJIjHSEFDy1UdrD+B7f5EU25SoSGkj8N6vT2izEqofYmRWxDkC+yFVu2mNrILzv2W+eCIplADTOfMGmaofumKMMR3daCB1POX7JZvi31q/LxodmPQ+16HNdkE1SYrZvV4s0oPuEe2GM0tgVH8BhhXNCNvAcL1r0vrQowkvqbv1pkw7GABycydk+cmwVha+dj/QsCJHD6/+N9Oi8xiFc7PQ1Z+o17o73QYPkQWqp+WB4/K6TJabilv+XmCiuhhlCzou+ixxZ8mxfsrxAhRpB+LNiio+wiFNX74fwznlmqSw7vsJ0lQpW4V2Uyzm1CkiE5drsAg7PEU+KFrbLc9zJhJiLQeBpzTILR4k63SScyeHnczFDp2EwyT3Cq4WHF2bKxbCP9zSnNyOZuQ0erQjuYJvJjKLVsN1gKuQfCcXbKidS3WkXSYdoYRgZyPPIQUeQJsmtn09yD9TOGzEj053GOEijgqA6SfRDvwHT9TKWU280ANhImnWRGqYmp+U9YUAmYUoIAjrqch
  template:
    metadata:
      name: adguardhome-sync-credentials
      namespace: external-services
    type: Opaque
