---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    root-password: AgBtyGmyYS5mvzrXt6S8Vhi7ZmVwYN5qDaBvHWtlUGObAdsd4GbK1khpu6hu+gnIzanoi4m1MIVHMY5KlYRiNR+i1j5o2n11Q7/mdTznq79vXcHLMkuFwqhIsd6vgJPZrs9IN5wrhVZ3uA/H6QUUBuj5UwbfJmvh7EsUJYLXQq+cUJOhYx8hB6+HLo+qPW1mrEDvnwZEt6k7YdEOCOSzBzwmnIFf1aZDZElomD8jy4PMvVgz3Mv3TBek+J6ru0oqxC5yKEAYWK2HiWLFrKaeONORqbdouQqmw3/N/K2gn3pV6EUyH0XMNl4eONM2lCbUctVp4/Mr1D9LlSNDhXwSN/EYUw7AzeRJMGFxIcVQyJB8I+giFSmKR/mjWJgRb6CGaZhLNOoKUJP3lgVnutpSc3a5sZEb5x9gv+xnvo0kM97eCWmbRWArQmly3IXq7CUt+PfK40x6dg7mX0gQIhqIcxxK5Omi+H5Y1cE/Z+DKuMLeGidr4DcusGczoLvIOEz7oY7rC5yNvAUmBUr/5AVbnIwqPKJcDRtoQByI93I+yonwN2pmRg7Sp+kGMQVBbxSnq37JeqIVcyVocgd7ZE+IVBlA8SdBTSMf6ARHSOoM+g5uANJkwGeWCoOLdHlKMgfPiNcTpR1ghNGD32szDulnZNs3SguMa4wzzliHuakgS0NRxZpzoyHWKUmmiirrXihuF1wo0xgVAJrUs+VbmNSwavFpxIJQPPMuWxeYBWV8wZKCuA==
    root-user: AgBDEtCojqRao0qioJkqJZwvLAYxJTZJMyvOdhku+kCzx881jDYI5dbxi7gbkH+lIR6kIlkc1m2qW14DC4UbleVvl9uuggg6hTddgKm1oOzPs2eulfjPi9Y5V6+Dbm5N+5NPY8rSb5hgSB+0uPUIP3pRPb1m2+tY8moS063/HiSanbUpM+lMbGni3uxcaLk+ZJVpDG3NbalEhm0OUB5ArT7KsD2CVBbo1QVhdPG8gTXYysOmsiwuCkU5giJpw6B18usvtwlRdvZpnRFePYdGICCZAe/AMMaDGxnezap0DEOiyKe9Wq8NQH7BhGUqXbccHadrcqAEysHsBn8pYUW8URhrnm4TAP4EqsaCCYj61wBZ4PcCzeP0r98bSDnstR5Gd4vqh39Bf9ibFrxy1o+HMCwjrg6LDbtazFuxIt7XG2l8zElHRfgCmJXOfHrq7111CUEWMBx6J6mqdqeWzwOm86WWtEKIXBe6xRtBcoGsHsjWOuax7dgF+pqc/fDqGCcLEnR+8fjgd8wDhMf1VL3uLfoYrvhxQ1s5L9hg+bmkkCJtXCdXixKu3/jfGF33zmbos3bCQLqJa44dwKmIstSf98YcyTvfGGTiTB5lCSGtFLcDBCwGYcnk2kVKhpfKREbT0SXhUBUV7vqHnSkJ9spTdjmH0dRAu4teJhNSq9160pHaU67aXC8pHbs51paMW/Gm/0DYro+cpe9mMAGCsA==
  template:
    metadata:
      name: minio-credentials
      namespace: minio
    type: Opaque
