---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    root-password: AgBCpT7mfX1lVX8qrbaEOj42LWEj6COVHygtZblGMP/z0q5nJycmX//86KzT8x/Nm+G6MSDZLUy29VPaLeYTxHRAUUSLH5wWKvERwI61wXUezxVijpvWY5PKFmOV8FOwXbUKA64UJP7x5geOpEbKHcFwapyFaT5hVLsMOwhqSiGEs6q4KmCLNf419CmidH8LmrYGeHb1bZzQd853AyZsWzUqyF455J313o1CPg5nqs0KgEkE0ATwb9ENWOyYbkuQysWQC89K6H4+LnaWvG2LLZx6BdJvxjNmkUp9AmE8gQqaM/WwHDFUxBGkVGv3qoW3FdCZmpP3RYSy0RS1W0nZKCkD3MWXTq+IKQ6hqU3gbn2ms2tsWJPTnKjbmpKhldZ48D6240Eu79TX5iwzy3kmkSjcXk8nc3Y4+hXBuPx9cOqiTMspcSsR3ntBd9XExCUBTzFoieK18tB8LgT/zImzp0gKI2EbsXbt4FgQqglFWBFBBZFOBrbGl23uLjedKdZji7KbWV4ISkql9/lphi4/snJJknGrTfdQ6jCMmw6qXMQimyzvPCIklkdLYiHu900GnQQHXEdABpT5epsaJKK37IkkSBGvLig+GzTtfNltTJPP17ZNchec9L61v/BdvZ1afCfIbIHHu3jLa7DZS5AKgWvdmDJcURIIvlOtTk27K/XjBya+WEVhpl4rsuKrNNvKRxXZ7nsiOg3ZEawKSDiu1fkaSmxWM+2c70Lt+ZFUcJ2FIQ==
    root-user: AgDBjvLbxp3aLbBS1g2o1RrMeFFogPSa8qYMt82dVUp9hsssg5pRT89ZbgQqhHtFTIAKpUbiXJYO0F/PK6E3NAKH6Mz0/KYvJ1ZXVPxfs6zwFMTaIgDDFN9ouYtmyFsUY7paB+oTdpSuNj4oX6i29AykuHu5bfk2ESIkQMqkkHWs/DdMchCkJ7UVOrTovBzRaOhzW2XZqREjvOlMYS/4WoSt7Fs3ZsGUtVwC4hvbywKHCP94icycR0IKLRkeZupUnXh6s1Gsa0U5xy9C7pjKNlCv8FaINX7bYKzI7H32I/u0atxBouvA44K8Kr72RnL4JQWB0RW62ihF8Te0TPj0Jj9DP7qvlMBZ+yhkxNkHyTYe73qidfEJ1COwA1Z93DhTq6qS2Nss6rcFhyfOW/UA9yk6mL55cDxe/sVCuwddFRV7s3qRV9XTWozu14aME6OH0Uo9kOKgxAQ43W1Q8l46uGxUMI1vAOzwN+pCEYDiKRWmXHIeJ2oPVkcnBw4bxEVJt0JkHdzN+BuCtKqflWpn1u5xzHNIOSmisl21XDT3oWqC5hXqdh7CXUgmVZ6Ye3iGn2g+fasx1vGr+xsEau+1y1kxYLMHv6zeROBz5oJ6iJkJa8t8BhVfk1Q54uF0+GW3ziYHCxfqnE5ofpkAmOz6wGMetXlGab2k6eCMrFxSDebKzfgGYQwndkZdOX7UEQ+r4mvO8bGs0ltPpJPjnw==
  template:
    metadata:
      name: minio-credentials
      namespace: minio
    type: Opaque
