---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: minio-upload
  namespace: minio
spec:
  buffering:
    maxRequestBodyBytes: 0
    maxResponseBodyBytes: 0
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-api
  namespace: minio
  annotations:
    cert-manager.io/cluster-issuer: internal-ca-issuer
    gethomepage.dev/enabled: "false"
    traefik.ingress.kubernetes.io/router.middlewares: minio-minio-upload@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - minio-api-k8s.elmstreet79.de
      secretName: minio-api-tls
  rules:
    - host: minio-api-k8s.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console
  namespace: minio
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: MinIO Console
    gethomepage.dev/description: S3 Management Console
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: minio.png
    gethomepage.dev/href: https://minio-k8s.elmstreet79.de
    gethomepage.dev/weight: "60"
    gethomepage.dev/pod-selector: "app=minio"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - minio-k8s.elmstreet79.de
      secretName: minio-console-tls
  rules:
    - host: minio-k8s.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9001
