apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/enable-real-ip: "true"
    nginx.ingress.kubernetes.io/real-ip-header: "X-Forwarded-For"
    nginx.ingress.kubernetes.io/set-real-ip-from: "192.168.0.0/16,10.42.0.0/16"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Home Assistant"
    gethomepage.dev/description: "Smart Home Hub"
    gethomepage.dev/group: "Applications"
    gethomepage.dev/icon: "home-assistant.png"
    gethomepage.dev/weight: "31"
    gethomepage.dev/ping: home-assistant.home-assistant.svc.cluster.local
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - homeassistant.elmstreet79.de
      secretName: home-assistant-tls
  rules:
    - host: homeassistant.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  name: http
