---
# Upgrade Control Plane Nodes first
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server-upgrade
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
      - key: kubernetes.io/hostname
        operator: NotIn
        values:
          - raspi4  # Already on v1.34.3
          - prodesk  # Already on v1.34.3
  serviceAccountName: system-upgrade
  version: v1.34.3+k3s1
  upgrade:
    image: rancher/k3s-upgrade
  drain:
    force: true
    ignoreDaemonSets: true
    deleteLocalData: true
---
# Upgrade Worker Nodes second
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent-upgrade
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/worker
        operator: Exists
      - key: kubernetes.io/hostname
        operator: NotIn
        values:
          - prodesk  # Already on v1.34.3
  serviceAccountName: system-upgrade
  version: v1.34.3+k3s1
  upgrade:
    image: rancher/k3s-upgrade
  drain:
    force: true
    ignoreDaemonSets: true
    deleteLocalData: true
