apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets.yaml
  - reloader.yaml
  - kured.yaml
  - coredns-config.yaml
  - metallb.yaml
  - metallb-config.yaml
  - cert-manager.yaml
  - cert-manager-config.yaml
  - traefik.yaml
  - longhorn.yaml
  - longhorn-config.yaml
  - kube-prometheus-stack.yaml
  - kube-prometheus-stack-config.yaml
  - unifi-poller.yaml
  - portainer.yaml
  - portainer-config.yaml
  - uptime-kuma.yaml
  - newt.yaml
  - newt-config.yaml
  - homepage.yaml
  - n8n.yaml
  - n8n-config.yaml
  - argocd-config.yaml
  - private-services.yaml
  - home-assistant.yaml
  - teslamate.yaml
  - landing-page.yaml
