apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets.yaml
  - reloader.yaml
  - kured.yaml
  - coredns-config.yaml
  - metallb.yaml
  - traefik.yaml
  - nfs-storage.yaml
  - longhorn.yaml
  - kube-prometheus-stack.yaml
  - proxmox-exporter.yaml
  - unifi-poller.yaml
  - portainer.yaml
  - uptime-kuma.yaml
  - homepage.yaml
  - n8n.yaml
  - argocd-config.yaml
  - private-services.yaml
  - home-assistant.yaml
  - teslamate.yaml
  - landing-page.yaml
  - beszel.yaml
  - fr24.yaml
  - paperless-ngx.yaml
  - newt.yaml
  - pangolin-sync.yaml
---

