apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets.yaml
  - reloader.yaml
  - coredns-config.yaml
  - metallb.yaml
  - metallb-config.yaml
  - cert-manager.yaml
  - cert-manager-config.yaml
  - nginx-ingress.yaml
  - nginx-ingress-config.yaml
  - longhorn.yaml
  - longhorn-config.yaml
  - kube-prometheus-stack.yaml
  - kube-prometheus-stack-config.yaml
  - unifi-poller-config.yaml
  - unifi-poller.yaml
  - portainer.yaml
  - portainer-config.yaml
  - uptime-kuma.yaml
  - uptime-kuma-config.yaml
  - homepage.yaml
  - homepage-config.yaml
  - argocd-config.yaml
  - private-services.yaml
  - home-assistant.yaml
  - teslamate.yaml
