apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "17"
spec:
  project: default
  source:
    repoURL: https://github.com/Nebu2k/kubernetes-homelab.git
    targetRevision: main
    path: overlays/production/n8n
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
