apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntfy-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "14"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Nebu2k/kubernetes-homelab.git
    targetRevision: main
    path: overlays/production/ntfy
  destination:
    server: https://kubernetes.default.svc
    namespace: ntfy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
