apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "16"
spec:
  project: default
  source:
    repoURL: https://github.com/Nebu2k/kubernetes-homelab.git
    targetRevision: main
    path: overlays/production/uptime-kuma
  destination:
    server: https://kubernetes.default.svc
    namespace: uptime-kuma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
