apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teslamate-grafana
  namespace: teslamate
  annotations:
    pangolin.io/expose: "true"
    pangolin.io/auth: "false"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "TeslaMate Grafana"
    gethomepage.dev/description: "Tesla Analytics Dashboards"
    gethomepage.dev/group: "Applications"
    gethomepage.dev/icon: "teslamate.png"
    gethomepage.dev/weight: "11"
    gethomepage.dev/pod-selector: "app=teslamate-grafana"
spec:
  ingressClassName: traefik
  rules:
    - host: teslamate.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teslamate-grafana
                port:
                  number: 3000
