apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teslamate
  namespace: teslamate
  annotations:
    pangolin.io/expose: "true"
    pangolin.io/auth: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "TeslaMate Settings"
    gethomepage.dev/description: "Tesla Tracking & Analytics"
    gethomepage.dev/group: "Applications"
    gethomepage.dev/icon: "teslamate.png"
    gethomepage.dev/weight: "10"
    gethomepage.dev/pod-selector: "app=teslamate"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - teslamate-settings.elmstreet79.de
      secretName: teslamate-tls
  rules:
    - host: teslamate-settings.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teslamate
                port:
                  number: 4000
