apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - proxmox-config.yaml
  - ingress.yaml
  - docker-ssh-secret-sealed.yaml
  - proxmox-secret-sealed.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: homepage
