apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - ingress.yaml
  - internal-ca-copy.yaml
  - proxmox-secret-sealed.yaml
  - argocd-token-secret-sealed.yaml
  - grafana-credentials-sealed.yaml
  - adguard-credentials-sealed.yaml
  - portainer-token-sealed.yaml
