apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-proxmox-config
  namespace: homepage
data:
  proxmox.yaml: |
    proxmox:
      url: https://192.168.2.8:8006
      token: {{HOMEPAGE_VAR_PROXMOX_USER}}
      secret: {{HOMEPAGE_VAR_PROXMOX_PASS}}
