env:
  HOMEPAGE_ALLOWED_HOSTS:
    value: "home.elmstreet79.de"
  NODE_EXTRA_CA_CERTS:
    value: "/certs/ca.crt"
  HOMEPAGE_VAR_PROXMOX_USER:
    valueFrom:
      secretKeyRef:
        name: homepage-proxmox
        key: username
  HOMEPAGE_VAR_PROXMOX_PASS:
    valueFrom:
      secretKeyRef:
        name: homepage-proxmox
        key: password
  HOMEPAGE_VAR_ARGOCD_TOKEN:
    valueFrom:
      secretKeyRef:
        name: argocd-homepage-token
        key: token
  HOMEPAGE_VAR_ADGUARD_USER:
    valueFrom:
      secretKeyRef:
        name: homepage-adguard
        key: username
  HOMEPAGE_VAR_ADGUARD_PASS:
    valueFrom:
      secretKeyRef:
        name: homepage-adguard
        key: password
  HOMEPAGE_VAR_PORTAINER_TOKEN:
    valueFrom:
      secretKeyRef:
        name: homepage-portainer
        key: token
  HOMEPAGE_VAR_UNIFI_USER:
    valueFrom:
      secretKeyRef:
        name: homepage-unifi
        key: username
  HOMEPAGE_VAR_UNIFI_PASS:
    valueFrom:
      secretKeyRef:
        name: homepage-unifi
        key: password
  HOMEPAGE_VAR_GRAFANA_USER:
    valueFrom:
      secretKeyRef:
        name: homepage-grafana
        key: username
  HOMEPAGE_VAR_GRAFANA_PASS:
    valueFrom:
      secretKeyRef:
        name: homepage-grafana
        key: password

# Mount Internal CA certificate
persistence:
  internal-ca:
    enabled: true
    type: secret
    name: internal-ca-secret
    mountPath: /certs
    readOnly: true
    defaultMode: 0444
