---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unifi-poller-config
  namespace: monitoring
spec:
  encryptedData:
    up.conf: AgAeDz15Ah//0xvjY/ql57mshyGM0r58XV5+6qVSRd2lhGIkw/nJTPCviZKpTNCQ53XAktD4Gsi3EQ6gvHVAKyL9GMPzqLjBCso53SU4tSN4ZUDJrTLxy9sUL+vYribEd3P5ZYT04WE6necWb4apUnq/NZcFT5B9MxRrNh3S5k61/kRf3Ld4xV50zyEphDOWWTKCvmSyZuThVYf5ZhG6kXg6Dg96GNpnrX7bNFqSVxVyyDWISdlFqSlYPc2+vSRER4yFbdQKB9MmVbzqnB4wuX1Ne0ZD6Aq3SFREXqQM7EqvYyOsM1/dtnsmp+dj0TWQg4jaBiLS5JpCpL3PDRzs4j5mhcFwV9ODtiyixaEfKUlFx3tVLOih3irsbgSyUKSqSqrcx8q/LjPc437rZNwraGHItW+CsZRaAQpLcXZzo6U9k3SXaVebsa/zGW32gKsg/1/SYTbRwGjLCuga9CnhdEITp8ZcKyOJasdrSpxEDrTzjb1cQqa1UmIpTuPZ9o7wDkzhfMConQCzfY0JXnuqdnidVdMB7PZHFC5riUMPsAk66QOTFE8XachaCxLbwB5g0B/gCVaUtGo5QJroytUJXlXhIcc7qyipuRehfqySqsUlA0CuD3a7WTInlMiN/IHtXyzDTdr72VYDWy86nwbZetZY4yyPF97IKP0Vtm8XzpM0TxCDdQI2pWVdGLcRHF/s8Vl7D2SLzYvl98RJFFdNt5Le8v7DbuOVmXYUeJLrckMdpvzuz0chwlqpwK+EXNjNZ3+TcY5TlyI7f8oCkE9BbdvWOQGsaRolQpEfF47I/6D7L3zoVPs+I18tAdIUcBWRGmibbE3Sy8bZO5q7Cy2T04tdGjoDex7x+/SEkkZevtwlcIkOUhB+ijtniLKdtjZXKQFuoSohgU5pl9W6o9feCVrtHj1+WwPjO13mjES3FRQFAai0UC+q6cpDDPknz8a6PSRHe6yvRramL7045P/l2z3WDvyDFn6xaGSxMXpL+P9VPQ1UI5S45nKv6WOZtfisbYZiCnF8N5WdFZRP2nzmcA8OvAcDKurqLTgZGQFUuwL8LPS6jcDqqrNJbf+rfQ66Va1NNk1jTkY5vxCSHm8Nh20vFb7gC/P6AmJGgcacUE4a47dzI7QqWTH+EAvZOovMvGMvQOlkYHd5ujXqeU3sp0tjnh827zIhzuuxOFU2dr4VjwZ9MJDw74GqJtbv/XAki2KU28xNHZ0kR1pSgnYWLW8zjQYdwKp1pP/Im8PPLDqUZD6Bb/Vqmnxr+2hq2w0b5H2PGZ0UyB1HMMPYigLBKsdFrQ2VJOMPMTtCDMZT17LcyQn87xLfpqOlIMXKa2OE8BdOekgW6EArGxXUEwOHBjXw2ii7fD5QpVhqa8p/KQ2zCXg5DstLlO7TGa7nZTxUrTdaMFDmZVAKpyUdKKX5ocYz36YFIh1x7G+AFFosudHYcQ7GnNNFOke0eV8Q5JYHSuZe
  template:
    metadata:
      name: unifi-poller-config
      namespace: monitoring
    type: Opaque
