---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unifi-poller-config
  namespace: monitoring
spec:
  encryptedData:
    up.conf: AgBce2m+uB8NU4NWZW7KtlIDMWl7MMLKdwWki99AQ1rcI4coFYa5geefBoekkRA8sz/WrLsWfOX31nPOXv8vmq9DhGtOEip91jYY2C2fLs+h3tPGUgrELX+YNypSS0NAvsrRyDqVPz1U44md6vuOJsh0GvAA28Loovtl4veL9BZMl3XfRZ95E4JetemZqWwt1rTodO6NWdNK4Zb6fwBM8QFXnQ3wJwUvZrAvzPBAJEt80jfHoQYW+UKWDArKp7dpT3cg8lAdo6dhAq8aSqSyuSXxfViVX4c5BScDdAm/HlITDUUEZppPDF1b9Ydn+js3YX6LoNe+7ai7dIohwZ5v+ziRXp/EHixJ6d6k01WuBi+RnT5PG61dZE/wRMRiZGpFrlDyiKs/MFCD6pWI9Nx/XWQ9TM/pJjKF/EoC4Umcys3Rjhajc+YTLv59iIysbClQt3lUCOFdFJW6pzJs4B1hiz5PH0xujLbqTK5Dadpvl9v9qHUwc11v9VkBGBfVqWvaeLc5JHoyvwG05aTfs3UzZCzCifUdEwMmWiaG6putIokOF86hJ6xswxDaPqtzkKHiGQ7n+ygjPBS1T4lEGCPmquGzEzfAJ/iG/miAPaqJA4DhE46MzPZAaJ2XydLdPpBrdNFGVT9Kw/2C5BJ86+7Dft0yjvbiL8ooLhxY0tA3P2KfELndaqqiO3D4spYdMS/0MlZYZzvY2qRXA+arowF5a9a2GOMUDnmbCcRK7qgs2z2gbcul96c+lAm1On+KLooRI8ffs/8+ZI4yIoTmkobCd8lJzrnEhAs3GqtflDUPBf/zV0lxVdH37mHf7aBZlCFXCOouUVMalGCbKQ3xih9vm5zugH90QmMYCEadIJCJI8zLT+JM66CYdfKfX6gWFgKFGpY2nMvBEB9l4XguIfQy1WdLkeuHQBjY2rbcNyvQ/lxWd54GQOHIkU05KVenKqUMs0SM3Sj5s7/+3UmWLP+kH6nbsOGrOLnWu6bjdFb95MnViVLahqhGQHTziDi6qySOWKHiHlZprMn7hYPafVMdog3rFJsH3m+to7alMguOYqB1DOAeXfZcYVN3j6m0eSZTre/ipYMYVfqhJGQ4LSye8Hdfk8VfPpS2vWkq8o+8p59PIb2oGYYJxwUVFd3xDlpETqtwyKhJOmFO9RhHsE/530Rc5P/uTbioPn5cRJhK8YlEqTIOG0W+3N7nGTtKH7DJFQVerZTUMIciqu2IgBuVkjr3+lAK07RDR9TRKjKhljlnlzJps2cwpCkQh77tth5BitDoAh+u/rqA87hBix7wf2eqMoQtHtkB/IVqSXW5gmaLV4vwSGan7IK8ottkXOoKb+fr9SqRDvJ++ZFxQ/hYCLB3+CHLn7rhkzg4SL6FpucA0c/CE8ewoVcGHZak/c864UXzOVekp25oD5DHR1W53v+Tq+cMD4z/SCkMutG8ozz5hwoK4EXq27lW
  template:
    metadata:
      name: unifi-poller-config
      namespace: monitoring
    type: Opaque
