apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
  annotations:
    cert-manager.io/cluster-issuer: "internal-ca-issuer"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Paperless-ngx"
    gethomepage.dev/description: "Document Management"
    gethomepage.dev/group: "Applications"
    gethomepage.dev/icon: "paperless-ngx.png"
    gethomepage.dev/weight: "60"
    gethomepage.dev/pod-selector: "app=paperless-ngx"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - paperless.elmstreet79.de
      secretName: paperless-ngx-tls
  rules:
    - host: paperless.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paperless-ngx
                port:
                  number: 80
