apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless-ngx
resources:
  - namespace.yaml
  - pvc.yaml
  - db-pvc.yaml
  - postgresql.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - paperless-secrets-sealed.yaml
