---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smb-credentials
  namespace: paperless-ngx
spec:
  encryptedData:
    password: AgAK3XCjxMvqgrzQL1enRequNyKs25mygeHGqHrX0+HYRGtpKZdWncRFR69AiiJ9cytJ+imlRNLK0qQDncT5/D0EN5K0bHwhFV0XV6n/x6XioKvYOg/N5CcSH/Hff4uqIgFaaeyiPxZi591YB1x7Zbs3PkTe5E/aFaTi48pC19oYPC27FdLxlK+kK53wtgjvgWxyTQiikMvAn30f4INOxt7Nh2DVTdRCJ4qdXWIPGaP7Q9IUsMg/wuMEX8Id5yHqPvCu+CsEFbvNcp2RVphJ8oUHdUSD/KkLI6+qp5MDqLWZmNc/Aa9EwA/hGrzQW1QQ2uItAhV8OsplhZFoa6eA/983x2JQKEg03MvOAIgPmRZdyyLzzXgoBtcSGVtdmisN11Q0b8c/7PDOb808d1WURbhbR4a81jqv7PLcVABoGzFC56VgD02glpm/XGYJiZpBeObdjmH5TlP3oIFtm4Fl+pPsQsfSPDES/wa1Tl1oIPWTtqYVbv3BF6BFlYlB5Tjj+PT8nQsiUNaZ06C/Mn4D5WkVXUwjifCUlTIBKMV8d9AceA/dRXe2C1zuqRuy5Oay0QUerZcLqKPMV7Uz9bXq8lFNEfo3v7Sp7IAXPGiJuC8p+gJ3y2vk1LMvT8GNkdZzrWqPifu96yBDe6Ttmm9lmzEfTEA73PlEIs1BKLU3AtQPzS/rqaDKhoasqMzBSFsBVgNN6QEnjLtDOLg7ukY=
    username: AgAJvNcH20h5IFEJCwSgtUgElUPxOTR14sbYxvAd4Zlw5Q1c86DCZrBtFDyIKD8JoG56AP0Uf2VXJ+7rwIs4cZy1G3ERB8ZXVHHg9oJbcn122iTDeNFu9qwKBL9CP73B1zEnnoMEB7qcYzfFurs/2PRpZEsdYx5rQp/19ulVvO7ISkDGLznbr2UgxZSM7YhaDkCmdTL++qYgQE0xgJ4RBW+7/G8t45TKc80R+W4MkwpfsRydTK7SZl5JO9muTaviK6RPnpr/v8XtIW5yZ04o01RJWmgdv9LVnu67Bubg1HwnG4mPj+04lXPMdYfbcOGpySUSFtskaWDwSK4wZ574QUMgbwK+DtzXQ4hyDC08QQg2oV2YB8D+ZaZg7uU/4oDpbMRMVe6leJSQUfR8G18wHphgZ5X+aTp4QM0hurmQ9QsB30zALgfbyerxG8CxqaH+UljvQa6xca401qs2xuBDkYnDO0rMKx6Z9PYqg6h/PcgS/2ElopuXcYZybJXav0GWntkdg9sXSgARzrlbKsyveipFXMCPehG7CAHoIk+HJ37+aGv/lGsCJ1hQarTdxkKQeYvIFdLF0CoGhUH6fOCOaTuXkjF4k1hX7kQ5NSBNOl936TSaTu7liP1K2/ocYsFEKajr4bcRDyVTLzvrKB+nyxflXRHfziB02OKEnA3StZihRhSGx+89iKzbz6D0K0o4PNyQSiBI1w==
  template:
    metadata:
      name: smb-credentials
      namespace: paperless-ngx
    type: Opaque
