---
apiVersion: v1
kind: Service
metadata:
  name: unifi-poller
  namespace: monitoring
  labels:
    app.kubernetes.io/name: unpoller
    app.kubernetes.io/instance: unifi-poller
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9130
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: unpoller
    app.kubernetes.io/instance: unifi-poller
