---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unifi-poller-config
  namespace: monitoring
spec:
  encryptedData:
    up.conf: AgBkuZPldvKPe7HBedOFL/YA7duXcNZpzTUDLc7eCLiqhb+q7YZxMovlu/Jyj+JKhE6Qu8GiFL/PKmigF7xLIG8OLldVK5kCGMgHdb+e8p6ZtPfzY8HxMqn9y2kvb/HhTqNAjyNUeTNnM9ixsM4Cw6BOclfJSHtdbiT3M6qFMYHVqi+b5eixt70sNXgmscmZl3bDJwJsEJcgLLz1VeUKuYMiKRWfO3svlVkk1gDREG3hySTUnWa8KvsxgtG4bRL/SOxaCEjcIusuQHJAKsvwq9rpxcZ6zChEr3rPz13ZJPOkaubx0WAkLS1lurjovtokxnYn+eBCYWbjqOzPf2DIfwtwFgjflpP6FeZbtqdeOK7ku65mPwnFRlJM66y0qnhVf52dBeSLolmeHX3XpauG+pwKVQW3wSqc4GoWvd3GKZE60ixGtI3X4PSQXxxI9gxsFvUTO/76RWeDxbwKw5MhaPP2byLjd+D24Fn/SPKpP5fl42V+flQEUsUnt95F1xm0NPeEhZDM1sSmqs7gfUrKEnQ+rQRlMg8rAuzElf9z6fSFX1m5wvn2+5l4ZEm4ZRmKzU5U2sFgFxEBIAqNugWW5su+tX/aQAju3JnhrRrYlTptjZK+3n06ijAag9S7Eh1ArIsQhR+0NOfAF280cJiHb9lu2GX3FweujwjN0RrjwfkQ/vVQUrkG+YnwM8Ekxt0mdLSg8R0UJyrXFReMUoDfGmQbZ4dQLUD8RBrxcBQl/A8l/+CFwkLMNalZ+XNgeLGhTakpQdjNU6VNmEy/IhVXFlbX4EeXOhjHaDeMCoKs0SQu7BmTLkxJH6cctz1ka4otsNq7qsxMd2+rE0s8RIYvQieXWij5LEbM7qe9tJoObQ6BQaoCNAN/0GuRgTBkBzKb+u1kTbXmUMMmPHJwLPCfeHQvKxZwCwX7tFVAngVJw/Rx0kk13Pb1lAg4caWnGWI1VJU4lGmaHKffe1CoGIjEJofMECTbsenJvR2Iuv6tkNTe8I+Xm7LLC9fmEmeaUI4aNv826kOiX6/UigBA1VmXQ4VKim125NoR3z7JaIEdDeI9Hr+5557Fpud40EvNtOnpGKcesXEIb49JgtHYr/v5k9X2JmdzUZKcaVi3RuApAdUi7AsIjKCcLm2VYOv8FFbuyR3sQOA8Z/TrggsjL+F1xoLM784DvHg0dWYqITRgk3Cq1lMkFkbJZsHc6SHbhkVdSsn6C/Z9KUJpUlv2u5VqzNUbJNpLkgBtPUwqt3r4kYTTd52IMQhmIyc3K1CephpggEPn/o5QFCKCbOo0M6D611rl+e9WXF4L/2iRqUvKy02THeiu8Mq69zAh+jQ/xd9KrRL5zrP4JBpb7izYhAblM1SOwtpulwCXI49VB7EweatYI1wjMgVSS7cBWvzdhbJm+yhkIpQzaHzME6ZBMf1RNN9FJjeHxY8/vdG0YdDkEPHZ6deHIPz1iCT+Q+pmmVesHwU/
  template:
    metadata:
      name: unifi-poller-config
      namespace: monitoring
    type: Opaque
