---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unifi-poller-config
  namespace: monitoring
spec:
  encryptedData:
    upConfig: AgC/+0glYCqZsF+Fu6sAFDOWzayOEz/4gNlv+vm9GlkbciSmqXU1AxznfKUnLvUSMo4gNBpOtsNACZgWfNArEALZq9UvDHvgegyZ5no/NLMdYkrwRwY63/7YfZT7P7sN+RA6AXiiQNHcZwjS9vqAnz9eX2UAG8RvfTTd0TAXKaT3adYuWTkpxlCgedTPk19SNg+JiQsw1OpOJvWpNugfMntPFHYxvMUi/PfDhUuMzcuezV3J5kOSX3RtckunHYIaeJyAhozLLEHkqKT486E6ItsW9g/qNqtbyX/8So9JLeM4Mg52UJMxFJrkpuE0p0L9fELstoiQ7E8odm3nrHl9JUtnWj4i1p6HTPVlZ0wHYlihYCXTeiBltXsVY/tfDcy/Rrq8BeHH4TXPdrbdGLwuc9W+LdVVAHvzjY5Odh3cE3Ct9ui9Kagx4mIM9Kso8kkVwiZhHy1JUt8RXQM6ZspZYVNNaDx67doc88v1JT7SvT35yFdc5F0EaL1DaITvEP52SPKW6qAX+esEypuGLdSyfM1rDGwwE6H9OdbihB5Aor27piyJg6a4M/u3ioopBUSuTUj311c5KK0NoA3zqHyv/emi3JSbH0f3vogiMM5bAsrGeYB7RWfpOL0wHNXooDSfLalyKmH+lNVZJceIxDhTHBOiV8g06l9dqfYMdzbFmGZCdR00LmCtm8AoCdf4hMa+jxhD0E7s709CqZGaBe9/crl/P6QXUnMbuKcB1VMc7Jw3Kkbu/rkHqfvceAaNKgyjnTe+zrIjACsXlFYLFQilLshmnesuNKyJj+bHeCdH0HaxK8mGhSWlBvwj3lEY0vBprwWSz44SJRD6ML8MQLsnaP9fFtnx2HnA13OAVQ17AACBISJF3RUGqmPmk8TX5LzPLBJ38oTmkvkEvVWUhbbMtq3HUKDsO0LKRa+6/ygswXKyn5sBhvP7T575qxw+DFC2Y9TnvmS+jZoy4Z6abmYrq5nbfte/Edn9amYcqpz2PFq62vethTOUGQqz6D0TWWdhOPtVkcUlzW61NEGmhGSUjae9sSxIoMpy/PNlFHksVTQJteYD9pp2dCc69uS2nuRz7/9x47Zvn2BspIHRaIFNLt8bFKhDZoWQkgc/QH9YVyo4KktPDBMwV4mmjcH1XmjHeQJsNvIlEaV5HhWDArjayKCeL1nA0wVz/SLqagG0yYiGgBSr+hJGo9mLTIZwW0VGu69GOrzwIVNPXIudf9HMkwfIDQd+5tWx3RCvCy1yqfmylhGCvWHp8pQqC5q60yEL+vczICOLrGXIcBlM4Z9LuDzomT/vN3+mOlcztx7vwCHAt7GvFYfrwi1FGScZIjWFqAma/6+Di3IHS54o7N6Su0uhuA0mWevTLU68c2KSmsoRnIPIAmAzkyvD+XYymmRDIm1F06+rBzEMdIftDgx2xrgwguebWf7fipw6u5zEG/jNrHJwynwySmQoOfTzS+aRdOERev2T
  template:
    metadata:
      name: unifi-poller-config
      namespace: monitoring
    type: Opaque
