---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unifi-poller-unpoller
  namespace: monitoring
spec:
  encryptedData:
    up.conf: AgA/ze1xaIZnq9eW6zNHGPABLrRRuzD8EIOx/SLE6ilPaIHyruyFWzrW1yPJFFCWqHNDXrLlcDeL47uuqXp7BW4V6jYrkL0qTD/CajiAtJYosB44WOF++q2KaWoPGS2RtPeQWZJ6D+eUdBbizsJIACOvynOuhojWuDRG/nVs9UFbF4r2ciOnoT/adKTWS4P8w7n0KJ1/RguwrivNogs6D9ep4mEJ9crKe0mzpJxxOVg8BLGy+5uYqVPE4C4wrHSsNPrSTgWRiTf4W3l39pvjacp2W220RpMa8A/lsmfQt1DfalG12sA2V6tmk2u7M9zOiFdNP3ImMTeiRtQOU8dsH/8qgxrY+t3XA02DyHhD+VstWfXD7mvzCZ73MK6w6y2bsVqsueZfnp8WmSYqeXRbJjqlfhqsm5+X2TfVu51DZagWOgZjVMCoQ5HNqPLVA6YUkRNkNg0tMxvoJbVsC4m5xXuYzgYW5HeIgKkplOa9UHawLF0mOXVL/HhVsnK1/dcJ4lvNZvyU7KnuUusv4FfoBW0Hwxs7veeMv9KQX1b5l9y4N6JJWYYU6JyWTQ3zr2z1o/qIQPmiLH/UGNC5xOdLjOJI9rokcz7ad5TYw5VLhdfCog2H+o1col69wrmvptnGjk9LSh0xGLxDWVbL1jJz7iei5OALF3CGeFb4fK4FSbAxvTw7NNKbZmlOAiyckfY+Kjp83Gk1hhoW/LnNOT8czdqJsdGsYFJY7wfQddv/jdEpfSgK4fqh+1ceVytOnt078hPAeN0Hro2MpYicKA/KW88Jift7pF9h2QaiJTF0G5nxpgxET/1QQCca4zAV5ur9MlP1BTwPPym6pjmlp9LUZI24Dt3N32VTH1UwKeJkXE070cpFw1TEvb2xqy+eHy7HEo1Jw7bDGCyU93Pw9LQm5N6ACq5S48cwUuN2skvOnXUJ9RJs8nwUkjrua9rJqDsmnk4Vzwdpp17WzpJuM3Dv6hm9kID1OX33UVKxdiiQCWJVpPyOsSlq6PY1Zqw0nimVNDmO7cq4pMmZ8GhfBsP8j5Vt8xvQiKDIdBnR+bmgSw9yT1ZIR9txxd+X/sdwYce60XeXSqbicKinySq07Lr9BRa9TzmmbCenudA/mdt5AMa4em9wLcucdKPnu55B/kC5PkQBFvvuO9tneCetCISQIhj0d9cuJxek2yUAE614XM8BLSV6yav1BLqhBRa/k1t+cpEz2obetcoPnr+nKEbwIPhg6Rwb9J5NgDtI29ah99hJ0Br4JYp+KCcOXvjv4THkDTOaLkA6NnsVKnESh9YRDPthOm+M8FJVAQKgZ/VWb15EXuuIqt8nVa8uxYX9zPGuLNY5gV1ERdbSu5/No3HyeQijvZCd7296omNEoEyOZKP7kxU8Uf4UCA6mcdhmWbhaNJFOTi+AltdvZGF2Whh03iKXV8o5olWpLujUnFMqc0VsJgDHHIb9B4oeDl8JJkT2HXmf7Evl
  template:
    metadata:
      name: unifi-poller-unpoller
      namespace: monitoring
    type: Opaque
