---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unifi-poller-config
  namespace: monitoring
spec:
  encryptedData:
    up.conf: AgAVmQLXGiyQbiQsenymDwlUs7k6crF8bU+6y9P7zpqlxE9gxumO4ZPXahyoI3F4MQIndjH1YJrqPOcxqfwGsJIYQU4LyRFCEX6TR+9lL7YQAgburGXWi7bVwrH2N6N9MKpPFVI3rXzOgzxcWfdD8C/GtPE38TgucEzqcu/lZUa3FC0il/mR+mEpQ3YYqgrdKZNRH0nc0jHtBuUt7P1+NFKLOZLs72Ph6n7GYg+A3msWPXZkszR+6RP84NJNL/sF6GDXd2CPoPzcfSfE7pD1Hv4rKXm/DA/eFRnC9KeGk+aF0Cm7O5trtY8yLOxiaqGQMgvB1w6RNbq9OfoIME2ejy9VPguafDnmrcSp9kNQ2amyVE+9UqRrirurCGRQbzU28dNEIwMbZxMvHH3Kxukg6XXO+nHV5p53gqBblOYPIpzUWR9/zj/k8YryMZIHDgngOk6V3HsQG63jhn8MPuajQVm7IW1BVqmwAMZm7K5vnHbFnFkWKvCtxPTQWNiJZA2nBPj/8vD8JnCe8MNczZ47SkCKl5W4+YS6+rb/Pk2VnQF0YU/5XRJTorkqQFlm2HiB4WU4NUDk2VJ6KJstScrZTJDNZMiUs+IorDNcXGzGwlKD5JYsIpb8p5C3Fj5Wt9RU1teGgFJW6otheNKndrk5kFJnQMGOmxpDudMiIIKZJcCc1wsOWNLb09mYmL99+UAfjDNPsNkWEUqcTzK15tfzWZYxagT9gec9J3m2et/3P346b0HsWJC8TcsUIuAQOMLjcqV7XUYnj8GsexwRf5jYLB+hS8Vg0sGBFSrCk9Gj3KsDHmDm5kTx57SRceptsCNvq89I6SEL+WIJv8dxvdhy7yEfS2slxpFdH4VZHn/9owSfPoJDPOAVfIgS5HhnnEsFRAzofzhTYsr7HrEInqvizj8pJStGkvE1xSU0UE0qzC6VznT18eUSCfFrKPoO9cbNFLJPO6QjlZzkWhSTAACJahDIH37KUbWnR0Ek9x2pJ4Bw2CR/fPyofhIWR5Qwdnops13pYOnS8fKBl19JDrMaAHCN1aIo3eUKeWOVCQvHqaM9UlkYoxf3fseq5jqXOmi/bv1iW/vPpipusDpMs1+4NpwhW4mXtI0R4WvRuwJ3m6peoNNZlKuNvuRBh0q/dgQB6DCxdfaXq9m4mYiRD/RvZdOgw6RF0fHXxOyfH9Jx86RGa+vpSO/3f+VW+m7OARUMxCRCOu1wvIqvnawZPfxcFF0ejrEC1AZ9JD5jTLB4yAm1YPjlSf/FNwSPW3GWNz33msfXyUKa+MIE8D8/DhZBF6k9HIFb08uAfnZE97EoVSeg09F1CPkvUcfSauowII/6vZtmog7qP1Yt1uwsJ4qGN15TKfpiRTNY8wDfSlrdbU65+eJxhSq7ao4CWq4G1ylphOiupYElMuh8xfXaJS1pEfPF1JMw+YFWH2GVvH+sPqiqewK8WhwxDTw+27dK8IosiAqZq3VW
  template:
    metadata:
      name: unifi-poller-config
      namespace: monitoring
    type: Opaque
