---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: blocky-api
  namespace: blocky
  labels:
    app.kubernetes.io/name: blocky
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`blocky.elmstreet79.de`)
      services:
        - name: blocky-api
          port: 4000
  tls:
    secretName: blocky-api-tls
---
apiVersion: v1
kind: Service
metadata:
  name: blocky-api
  namespace: blocky
  labels:
    app.kubernetes.io/name: blocky
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 4000
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: blocky
