---
apiVersion: v1
kind: Service
metadata:
  name: blocky-dns-udp
  namespace: blocky
  labels:
    app.kubernetes.io/name: blocky
    app.kubernetes.io/component: dns
  annotations:
    metallb.universe.tf/allow-shared-ip: blocky-dns
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.2.251
  externalTrafficPolicy: Local
  ports:
  - name: dns-udp
    port: 53
    targetPort: dns-udp
    protocol: UDP
  selector:
    app.kubernetes.io/name: blocky
