---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blocky-api-tls
  namespace: blocky
spec:
  secretName: blocky-api-tls
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - blocky.elmstreet79.de
