---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blocky
resources:
  - namespace.yaml
  - redis-pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - blocky-configmap.yaml
  - blocky-custom-dns-configmap.yaml
  - blocky-deployment.yaml
  - blocky-service-tcp.yaml
  - blocky-service-udp.yaml
  - blocky-ingress.yaml
  - certificate.yaml
  - servicemonitor.yaml
  - grafana-dashboard.yaml
