apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: "internal-ca-issuer"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Homepage integration
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: "Applications - Intern"
    gethomepage.dev/name: "AlertManager"
    gethomepage.dev/icon: "alertmanager.png"
    gethomepage.dev/description: "Alert Management"
    gethomepage.dev/weight: "21"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - alertmanager.elmstreet79.de
      secretName: alertmanager-tls
  rules:
    - host: alertmanager.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-alertmanager
                port:
                  number: 9093
