---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgALc+Yr1/037oQNg+m3eTSOZ4UBvYlaybS/NwnVfW6UOpdyvBlGw8apjiutqQK8reJrInJg8tia7iaTtTCiSjTtFhouiYxjTfqzH9SC14BBc5fRqeGT+p+u6EGVcCUHJGPZRB3cQ5Xhr5DlJoT2kILOW8oVfGmpaIK1QeCJG0doAMRWRDvIyAL0ti0ua0/lxCWOyWCLCTKZ3YyyChJq5Zl+d5ylcq7lXHtq1HEjjBrZTMwvYoovdsADA9TZ7/Stujc0n8GyNGfDrNvT5R/Ce4p/mOhGNHAhT0mFCR+MTC5AfdBDn5dcY/Kjf0TPHYGrbfQViWe4SAod9nd+Z5q1ftNWDy0HaKBHRMz4th86tF412t5TseBMnZR8Rduo82yZXwaCR62RxrppAEpiBK0ETsYKNizCL/K+tQZy1CFWJkERwMTkJwbz3HmY0Nxvxjy77Khpmj6ksgrfgPsIkvaOhcbp6YWi2Knh7iui2Np8Oq7osdlOys/K4dKlRHni3hDpomRBKx+SE5kc6hDij6zQ7rYq1sJhSrZJM0WxWH8cna4Jl5bDTjBR9h5NvdkXr6l1ic72pymqLwFHVmTw98DAQFsuXa8LoJJh/od/3dlsPB8djUdRBoVjwtVrl895PY04syAbKymA00q2KMDfxnbSv0q8VvV5fKHfjXIZ0oUZRtIemqIEuvs1MK/LWDwMCQbqOpV7L5MllBTuuOVvA0TDyJyA3Bh6uUmBRKA9mk4=
    admin-user: AgDC7kgWyxeHra+7NQUprmmdQ2f53KfK9SN4v261ARro+9txHBwcQCLjVmlzaPCYfqPNH0LQncm7F+CAcvMraTQM/9umgdbqYjGNkAaAcq9LizC7XW1WOzuMJJtvJUZ6TuIud3QBk70jsIujMoFJKCLJZPIQu+GUpQ1gp2/TBQ6lrKCE63iYKbEScynMWe8Z8pKZQmchDYSu2GwxB2Aqb8byMwh9t6QCZUlrElcup5y9d+cuT2/io2kW4T2OLXZc9zsLyx1wxMTSGPJTgNWRCs53hEviq1EZh30lvnn6bstDQcyLopAzmN+BWoAYbTSs1Vr3OhKP2dZmD74ahAO60U2ZhDiWwIi5n2BkdX8zvB084CMTL4d+t3Wi9LLlL6FYiqqdngdpqnR5nsaKIgCPYfT8NpvuVNDSUjO5qcnx3joC6AF/r9f33nZ9aKLLQRNIEDj0XhgbE0zoJinAdNks9Doqg+Z/s1Y4GCSj+5Rt/NAbH6nE49TaS8M+nBS7skazA1wKU+PXHP1IO+Gh1kxolMx2nHAagkyoPPHjePy7k9LdE+vZedS7j+99W0JFxRiUwUFLyUOyDlHBr3HiQvteRktIPYaHyZNSjtnPrNTrVzWMvP3pOgq+6olx2ugz1Bi4hsnVuMYxNw33u6JRn9bFxp+L+/eUg/scGrcamF33ilk8c/mRB7E3CvZ+piTdCW0gctR08K4pNQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
