apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: "internal-ca-issuer"
    # Homepage integration
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: "Applications - Intern"
    gethomepage.dev/name: "Prometheus"
    gethomepage.dev/icon: "prometheus.png"
    gethomepage.dev/description: "Metrics Database"
    gethomepage.dev/weight: "20"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - prometheus.elmstreet79.de
      secretName: prometheus-tls
  rules:
    - host: prometheus.elmstreet79.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-prometheus
                port:
                  number: 9090
